#!/usr/bin/env python3
"""
Chatterbox duration estimator
=============================

A high-accuracy duration-estimation toolkit for the original English
ResembleAI Chatterbox TTS model (the model with exaggeration + cfg_weight).

It provides three accuracy levels:

1) heuristic
   Zero-training fallback. Fast, but not intended for precision work.

2) learned
   Trains an ensemble on T3 speech-token counts generated by YOUR exact
   Chatterbox voice and parameter range.  The model predicts speech-token
   count, then converts it to seconds using Chatterbox's 25 Hz speech-token
   rate.

3) probe
   Runs Chatterbox's autoregressive T3 stage but skips S3Gen waveform
   decoding.  This obtains the actual generated speech-token count.
   Because Chatterbox speech tokens are 25 Hz, this is the closest thing
   to an exact pre-vocoder duration prediction.  For a hard guarantee,
   reuse the probed speech tokens for waveform synthesis rather than
   re-running T3.

IMPORTANT
---------
A universal "<1% error for every utterance, no matter the duration" guarantee
is impossible for a pure text regressor.  For a 1-second utterance, 1% is only
10 ms, smaller than one Chatterbox speech-token frame (40 ms).

If you need near-exact final timing:
  * use the learned model for the large parameter/text search;
  * use T3 token probing for the final few candidates;
  * synthesize the selected candidate from the SAME probed token sequence.

The learned model is deliberately trained/tested with GROUP SPLITS BY TEXT.
Different exaggeration/CFG versions of the same sentence can never appear in
both train and test sets.

Typical workflow
----------------

# 1. Build calibration data.  Using your real narration corpus is strongly
#    recommended. One text per line or ordinary paragraphs are accepted.
python chatterbox_duration_estimator.py collect \
    --voice-ref voice.wav \
    --corpus narration_corpus.txt \
    --out duration_data.csv \
    --texts 1800 \
    --variants-per-text 5 \
    --device cuda

# 2. Train + evaluate
python chatterbox_duration_estimator.py train \
    --data duration_data.csv \
    --model duration_model.joblib

# 3. Fast prediction
python chatterbox_duration_estimator.py predict \
    --model duration_model.joblib \
    --text "Keep a safe distance from moving machinery." \
    --exaggeration 0.50 \
    --cfg-weight 0.50

# 4. T3-only final probe
python chatterbox_duration_estimator.py probe \
    --voice-ref voice.wav \
    --text "Keep a safe distance from moving machinery." \
    --exaggeration 0.50 \
    --cfg-weight 0.50 \
    --seed 1234

Integration with safety_montage_narrator.py
-------------------------------------------
Set:

    export CHATTERBOX_DURATION_MODEL=/absolute/path/duration_model.joblib

Then use:

    --estimator chatterbox_duration_estimator:estimate_duration

The function:
    estimate_duration(text, exaggeration, cfg_weight) -> float
matches the adapter expected by the montage pipeline.
"""

from __future__ import annotations

import argparse
import csv
import gc
import hashlib
import json
import math
import os
import random
import re
import statistics
import sys
import time
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Optional, Sequence

import numpy as np


# ---------------------------------------------------------------------------
# Text helpers
# ---------------------------------------------------------------------------

WORD_RE = re.compile(r"[A-Za-z]+(?:['’-][A-Za-z]+)*|\d+(?:[.,]\d+)*")
SENTENCE_SPLIT_RE = re.compile(r"(?<=[.!?])\s+")
VOWEL_GROUP_RE = re.compile(r"[aeiouy]+", re.I)
ACRONYM_RE = re.compile(r"\b(?:[A-Z]\.?){2,}\b")
NUMBER_RE = re.compile(r"\b\d+(?:[.,]\d+)*(?:%|°[CF])?\b")
URL_RE = re.compile(r"(?:https?://|www\.)\S+", re.I)
EMAIL_RE = re.compile(r"\b[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}\b")


def normalize_space(text: str) -> str:
    return re.sub(r"\s+", " ", str(text)).strip()


def normalize_key(text: str) -> str:
    t = normalize_space(text).lower().replace("’", "'")
    return hashlib.sha1(t.encode("utf-8")).hexdigest()


def words(text: str) -> list[str]:
    return WORD_RE.findall(text)


def hard_wrap(text: str, max_chars: int = 280) -> list[str]:
    """Sentence-aware splitting similar to the montage pipeline."""
    text = normalize_space(text)
    if not text:
        return []
    sentences = [s.strip() for s in SENTENCE_SPLIT_RE.split(text) if s.strip()]
    if not sentences:
        sentences = [text]

    pieces: list[str] = []
    for sentence in sentences:
        if len(sentence) <= max_chars:
            pieces.append(sentence)
            continue

        # Prefer clauses, then words.
        clauses = re.split(r"(?<=[,;:])\s+", sentence)
        cur = ""
        for clause in clauses:
            if len(clause) > max_chars:
                for w in clause.split():
                    proposal = w if not cur else cur + " " + w
                    if len(proposal) <= max_chars:
                        cur = proposal
                    else:
                        if cur:
                            pieces.append(cur)
                        cur = w
            else:
                proposal = clause if not cur else cur + " " + clause
                if len(proposal) <= max_chars:
                    cur = proposal
                else:
                    if cur:
                        pieces.append(cur)
                    cur = clause
        if cur:
            pieces.append(cur)

    out: list[str] = []
    cur = ""
    for piece in pieces:
        proposal = piece if not cur else cur + " " + piece
        if len(proposal) <= max_chars:
            cur = proposal
        else:
            if cur:
                out.append(cur)
            cur = piece
    if cur:
        out.append(cur)
    return [x for x in out if x]


# ---------------------------------------------------------------------------
# Pronunciation / linguistic features
# ---------------------------------------------------------------------------

_CMU = None


def _get_cmudict():
    global _CMU
    if _CMU is None:
        try:
            import cmudict
            _CMU = cmudict.dict()
        except Exception:
            _CMU = {}
    return _CMU


def heuristic_syllables(word: str) -> int:
    w = re.sub(r"[^a-z]", "", word.lower())
    if not w:
        return 0
    groups = len(VOWEL_GROUP_RE.findall(w))
    if len(w) > 3 and w.endswith("e") and not w.endswith(("le", "ye")):
        groups -= 1
    if w.endswith("ed") and len(w) > 4 and not w.endswith(("ted", "ded")):
        groups -= 1
    return max(1, groups)


def pronunciation_stats(text: str) -> dict[str, float]:
    cmu = _get_cmudict()
    toks = [re.sub(r"[^A-Za-z']", "", w).lower() for w in words(text)]
    toks = [w for w in toks if w and any(ch.isalpha() for ch in w)]

    phoneme_count = 0
    vowel_phonemes = 0
    stressed = 0
    cmu_hits = 0
    syllables = 0

    for w in toks:
        lookup = w
        if lookup.endswith("'s"):
            lookup = lookup[:-2]
        prons = cmu.get(lookup)
        if prons:
            pron = prons[0]
            cmu_hits += 1
            phoneme_count += len(pron)
            v = sum(1 for p in pron if p and p[-1:].isdigit())
            vowel_phonemes += v
            syllables += v
            stressed += sum(1 for p in pron if p.endswith(("1", "2")))
        else:
            syl = heuristic_syllables(w)
            syllables += syl
            vowel_phonemes += syl
            # A spelling-based phoneme-count approximation.
            phoneme_count += max(syl, round(0.68 * len(w) + 0.6 * syl))

    n = max(1, len(toks))
    return {
        "phoneme_count": float(phoneme_count),
        "vowel_phonemes": float(vowel_phonemes),
        "stressed_syllables": float(stressed),
        "syllable_count": float(syllables),
        "cmu_hit_ratio": float(cmu_hits / n),
        "phonemes_per_word": float(phoneme_count / n),
        "syllables_per_word": float(syllables / n),
    }


def text_feature_dict(
    text: str,
    exaggeration: float,
    cfg_weight: float,
) -> dict[str, float]:
    text = normalize_space(text)
    toks = words(text)
    alpha_words = [w for w in toks if any(c.isalpha() for c in w)]
    lengths = [len(re.sub(r"[^A-Za-z]", "", w)) for w in alpha_words]
    n_words = len(toks)
    n_alpha_words = len(alpha_words)
    n_chars = len(text)
    n_letters = sum(c.isalpha() for c in text)
    n_digits = sum(c.isdigit() for c in text)
    n_spaces = sum(c.isspace() for c in text)
    n_upper = sum(c.isupper() for c in text)
    n_lower = sum(c.islower() for c in text)

    sentence_end = sum(text.count(x) for x in ".!?")
    comma = text.count(",")
    semicolon = text.count(";")
    colon = text.count(":")
    dash = text.count("-") + text.count("—") + text.count("–")
    quote = sum(text.count(x) for x in ['"', "“", "”"])
    apostrophe = text.count("'") + text.count("’")
    parens = sum(text.count(x) for x in "()[]{}")
    slash = text.count("/") + text.count("\\")
    ellipsis = text.count("...") + text.count("…")
    newline = str(text).count("\n")

    p = pronunciation_stats(text)

    unique_words = len({w.lower() for w in toks})
    mean_word_len = float(np.mean(lengths)) if lengths else 0.0
    std_word_len = float(np.std(lengths)) if lengths else 0.0
    max_word_len = max(lengths) if lengths else 0

    f: dict[str, float] = {
        "chars": float(n_chars),
        "letters": float(n_letters),
        "digits": float(n_digits),
        "spaces": float(n_spaces),
        "words": float(n_words),
        "alpha_words": float(n_alpha_words),
        "unique_words": float(unique_words),
        "unique_word_ratio": float(unique_words / max(1, n_words)),
        "mean_word_len": mean_word_len,
        "std_word_len": std_word_len,
        "max_word_len": float(max_word_len),
        "short_words_1_3": float(sum(1 <= x <= 3 for x in lengths)),
        "medium_words_4_6": float(sum(4 <= x <= 6 for x in lengths)),
        "long_words_7_9": float(sum(7 <= x <= 9 for x in lengths)),
        "very_long_words_10p": float(sum(x >= 10 for x in lengths)),
        "sentence_end": float(sentence_end),
        "commas": float(comma),
        "semicolons": float(semicolon),
        "colons": float(colon),
        "dashes": float(dash),
        "quotes": float(quote),
        "apostrophes": float(apostrophe),
        "parens": float(parens),
        "slashes": float(slash),
        "ellipsis": float(ellipsis),
        "newlines": float(newline),
        "acronyms": float(len(ACRONYM_RE.findall(text))),
        "numbers": float(len(NUMBER_RE.findall(text))),
        "urls": float(len(URL_RE.findall(text))),
        "emails": float(len(EMAIL_RE.findall(text))),
        "uppercase_ratio": float(n_upper / max(1, n_letters)),
        "lowercase_ratio": float(n_lower / max(1, n_letters)),
        "digit_ratio": float(n_digits / max(1, n_chars)),
        "punctuation_total": float(sum(not c.isalnum() and not c.isspace() for c in text)),
        "clause_marks": float(comma + semicolon + colon + dash),
        "pause_marks": float(sentence_end + comma + semicolon + colon + ellipsis),
        "exaggeration": float(exaggeration),
        "cfg_weight": float(cfg_weight),
        "exag_sq": float(exaggeration * exaggeration),
        "cfg_sq": float(cfg_weight * cfg_weight),
        "exag_x_cfg": float(exaggeration * cfg_weight),
        "words_x_exag": float(n_words * exaggeration),
        "words_x_cfg": float(n_words * cfg_weight),
        "chars_x_exag": float(n_chars * exaggeration),
        "chars_x_cfg": float(n_chars * cfg_weight),
    }
    f.update(p)

    # Letter-distribution features help with pronunciation on words absent from CMUdict.
    lower = text.lower()
    denom = max(1, n_letters)
    for ch in "abcdefghijklmnopqrstuvwxyz":
        f[f"letter_{ch}_ratio"] = float(lower.count(ch) / denom)

    # Densities are useful for extrapolating across text length.
    wden = max(1, n_words)
    for key in (
        "sentence_end", "commas", "semicolons", "colons", "dashes",
        "ellipsis", "numbers", "acronyms", "pause_marks", "syllable_count",
        "phoneme_count",
    ):
        f[f"{key}_per_word"] = float(f[key] / wden)

    return f


def heuristic_duration(text: str, exaggeration: float = 0.5, cfg_weight: float = 0.5) -> float:
    """
    Rule-based fallback. It is intentionally conservative and is NOT the
    precision estimator.
    """
    f = text_feature_dict(text, exaggeration, cfg_weight)
    syllables = f["syllable_count"]
    # Rough neutral speech rate, then small control corrections in the
    # direction documented for Chatterbox (higher exaggeration tends faster;
    # lower CFG is commonly used to slow/steady pace).
    syllables_per_second = 4.35
    speed = 1.0 + 0.12 * (exaggeration - 0.5) + 0.10 * (cfg_weight - 0.5)
    speed = max(0.70, min(1.30, speed))
    lexical = syllables / (syllables_per_second * speed)

    pauses = (
        0.12 * f["commas"]
        + 0.18 * f["semicolons"]
        + 0.16 * f["colons"]
        + 0.24 * f["sentence_end"]
        + 0.20 * f["ellipsis"]
    )
    return max(0.20, lexical + pauses)


# ---------------------------------------------------------------------------
# TTS token probe
# ---------------------------------------------------------------------------

def set_all_seeds(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    import torch
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)


class ChatterboxTokenProbe:
    """
    Loads original English Chatterbox and exposes its T3 speech-token sequence.

    This intentionally mirrors ChatterboxTTS.generate up to (but not including)
    S3Gen decoding.
    """

    def __init__(
        self,
        device: str = "cuda",
        voice_ref: Optional[str] = None,
    ):
        import torch
        import torch.nn.functional as F
        from chatterbox.tts import ChatterboxTTS, punc_norm
        try:
            from chatterbox.models.s3tokenizer import S3_TOKEN_RATE, drop_invalid_tokens
        except ImportError:
            # Older package variants exposed drop_invalid_tokens elsewhere.
            from chatterbox.models.s3tokenizer import drop_invalid_tokens
            S3_TOKEN_RATE = 25
        from chatterbox.models.t3.modules.cond_enc import T3Cond

        self.torch = torch
        self.F = F
        self.punc_norm = punc_norm
        self.drop_invalid_tokens = drop_invalid_tokens
        self.T3Cond = T3Cond
        self.token_rate = int(S3_TOKEN_RATE)
        self.device = device

        self.model = ChatterboxTTS.from_pretrained(device=device)
        self.voice_ref = voice_ref
        if voice_ref:
            self.model.prepare_conditionals(voice_ref, exaggeration=0.5)
        elif self.model.conds is None:
            raise ValueError(
                "No --voice-ref was supplied and this Chatterbox checkpoint "
                "does not contain built-in conditionals."
            )

    def _set_exaggeration(self, exaggeration: float) -> None:
        torch = self.torch
        old = self.model.conds.t3
        current = float(old.emotion_adv[0, 0, 0].item())
        if abs(current - float(exaggeration)) < 1e-8:
            return
        self.model.conds.t3 = self.T3Cond(
            speaker_emb=old.speaker_emb,
            cond_prompt_speech_tokens=old.cond_prompt_speech_tokens,
            emotion_adv=float(exaggeration) * torch.ones(1, 1, 1),
        ).to(device=self.model.device)

    @staticmethod
    def _speech_vocab_limit() -> int:
        # Current original Chatterbox uses valid S3 IDs < 6561.
        return 6561

    def probe_tokens(
        self,
        text: str,
        exaggeration: float = 0.5,
        cfg_weight: float = 0.5,
        temperature: float = 0.8,
        repetition_penalty: float = 1.2,
        min_p: float = 0.05,
        top_p: float = 1.0,
        seed: int = 1234,
        max_new_tokens: int = 1000,
    ):
        torch = self.torch
        F = self.F

        self._set_exaggeration(exaggeration)
        text = self.punc_norm(text)
        text_tokens = self.model.tokenizer.text_to_tokens(text).to(self.model.device)

        if cfg_weight > 0.0:
            text_tokens = torch.cat([text_tokens, text_tokens], dim=0)

        sot = self.model.t3.hp.start_text_token
        eot = self.model.t3.hp.stop_text_token
        text_tokens = F.pad(text_tokens, (1, 0), value=sot)
        text_tokens = F.pad(text_tokens, (0, 1), value=eot)

        set_all_seeds(seed)
        with torch.inference_mode():
            speech_tokens = self.model.t3.inference(
                t3_cond=self.model.conds.t3,
                text_tokens=text_tokens,
                max_new_tokens=max_new_tokens,
                temperature=temperature,
                cfg_weight=cfg_weight,
                repetition_penalty=repetition_penalty,
                min_p=min_p,
                top_p=top_p,
            )

        speech_tokens = speech_tokens[0]
        # Current drop_invalid_tokens implementations have differed slightly;
        # be defensive and then apply the explicit vocabulary bound.
        try:
            speech_tokens = self.drop_invalid_tokens(speech_tokens)
        except Exception:
            speech_tokens = speech_tokens[speech_tokens < self._speech_vocab_limit()]
        speech_tokens = speech_tokens[speech_tokens < self._speech_vocab_limit()]
        return speech_tokens.to(self.model.device)

    def token_duration_seconds(self, speech_tokens) -> float:
        return float(speech_tokens.numel()) / float(self.token_rate)

    def probe_duration(self, *args, **kwargs) -> tuple[float, int]:
        tokens = self.probe_tokens(*args, **kwargs)
        return self.token_duration_seconds(tokens), int(tokens.numel())

    def waveform_duration_from_tokens(self, speech_tokens) -> float:
        """Decode exactly these tokens and measure waveform duration."""
        torch = self.torch
        with torch.inference_mode():
            wav, _ = self.model.s3gen.inference(
                speech_tokens=speech_tokens,
                ref_dict=self.model.conds.gen,
            )
        return float(wav.shape[-1]) / float(self.model.sr)

    def save_tokens(self, speech_tokens, path: str | Path) -> None:
        self.torch.save(speech_tokens.detach().cpu(), str(path))

    def close(self) -> None:
        try:
            del self.model
        except Exception:
            pass
        gc.collect()
        if self.torch.cuda.is_available():
            self.torch.cuda.empty_cache()


# ---------------------------------------------------------------------------
# Corpus + synthetic calibration text generation
# ---------------------------------------------------------------------------

SUBJECTS = [
    "workers", "operators", "visitors", "technicians", "drivers", "pedestrians",
    "staff members", "maintenance personnel", "contractors", "supervisors",
    "anyone entering the area", "people nearby",
]
ACTIONS = [
    "keep a safe distance from moving equipment",
    "wear appropriate eye protection",
    "use hearing protection where required",
    "keep hands clear of moving parts",
    "check the area before starting the machine",
    "follow the marked pedestrian route",
    "secure loose clothing and long hair",
    "disconnect power before maintenance",
    "inspect protective equipment before use",
    "report damaged guards immediately",
    "keep emergency exits unobstructed",
    "maintain three points of contact on ladders",
    "store hazardous materials in the designated location",
    "verify that the work surface is stable",
    "keep ignition sources away from flammable material",
    "use the correct lifting technique",
    "confirm that the guard is in position",
    "avoid standing beneath suspended loads",
    "wash hands after handling chemicals",
    "read the posted instructions before proceeding",
]
CONTEXTS = [
    "before work begins", "while the equipment is operating", "during maintenance",
    "when visibility is limited", "in high-traffic areas", "near loading zones",
    "whenever the warning light is active", "before entering the restricted area",
    "when handling unfamiliar equipment", "during routine inspections",
]
CONSEQUENCES = [
    "This reduces the chance of accidental contact.",
    "The precaution is especially important when several activities occur at once.",
    "Do not assume that another person has already checked the hazard.",
    "Stop and reassess the situation if conditions change.",
    "The warning remains relevant even during a short task.",
    "Follow the site procedure rather than relying on memory alone.",
    "If the condition cannot be made safe, do not continue until it is corrected.",
]
TRANSITIONS = [
    "In addition", "At the same time", "Before proceeding", "Where applicable",
    "For nearby personnel", "During normal operation", "As conditions change",
    "For the next step", "In restricted areas", "For short tasks as well",
]


def synthetic_text(rng: random.Random, min_words: int = 8, max_words: int = 55) -> str:
    target = rng.randint(min_words, max_words)
    sentences: list[str] = []

    while len(words(" ".join(sentences))) < target:
        subject = rng.choice(SUBJECTS)
        action = rng.choice(ACTIONS)
        context = rng.choice(CONTEXTS)
        structure = rng.randrange(6)

        if structure == 0:
            s = f"{subject.capitalize()} should {action} {context}."
        elif structure == 1:
            s = f"{rng.choice(TRANSITIONS)}, {action} {context}; check the surrounding area first."
        elif structure == 2:
            s = f"Warning: {action}. {rng.choice(CONSEQUENCES)}"
        elif structure == 3:
            n = rng.choice([2, 3, 5, 10, 15, 30])
            s = f"{action.capitalize()} {context}, and maintain at least {n} feet of clearance when the posted rule requires it."
        elif structure == 4:
            s = f"Before continuing, {action}; then confirm that nearby {rng.choice(SUBJECTS)} understand the restriction."
        else:
            s = f"{action.capitalize()} {context}. {rng.choice(CONSEQUENCES)}"

        if rng.random() < 0.12:
            s += f" Section {rng.randint(1, 12)}.{rng.randint(1, 9)} may provide additional instructions."
        if rng.random() < 0.08:
            s += " PPE requirements can change with the task."
        sentences.append(s)

    out = normalize_space(" ".join(sentences))
    if len(out) > 280:
        chunks = hard_wrap(out, 280)
        out = rng.choice(chunks)
    return out


def read_corpus(paths: Sequence[str], max_chars: int = 280) -> list[str]:
    out: list[str] = []
    for pstr in paths:
        p = Path(pstr)
        raw = p.read_text(encoding="utf-8", errors="replace")

        if p.suffix.lower() == ".jsonl":
            items = []
            for line in raw.splitlines():
                if not line.strip():
                    continue
                obj = json.loads(line)
                if isinstance(obj, dict) and isinstance(obj.get("text"), str):
                    items.append(obj["text"])
                elif isinstance(obj, str):
                    items.append(obj)
            raw_blocks = items
        else:
            # Preserve paragraphs but also handle one-text-per-line corpora.
            raw_blocks = [x.strip() for x in re.split(r"\n\s*\n|\n", raw) if x.strip()]

        for block in raw_blocks:
            for chunk in hard_wrap(block, max_chars=max_chars):
                if 3 <= len(words(chunk)) <= 90:
                    out.append(chunk)

    seen: set[str] = set()
    unique: list[str] = []
    for t in out:
        k = normalize_key(t)
        if k not in seen:
            seen.add(k)
            unique.append(t)
    return unique


# ---------------------------------------------------------------------------
# Data collection
# ---------------------------------------------------------------------------

DATA_FIELDS = [
    "text_id", "text", "exaggeration", "cfg_weight", "seed",
    "temperature", "repetition_penalty", "min_p", "top_p",
    "speech_tokens", "token_rate", "duration_s",
    "waveform_duration_s", "waveform_error_pct",
]


def _control_points(
    rng: random.Random,
    variants: int,
    exag_min: float,
    exag_max: float,
    cfg_min: float,
    cfg_max: float,
) -> list[tuple[float, float]]:
    # Anchor points make the response surface identifiable; jittered points
    # cover the rest continuously.
    anchors = [
        (0.50, 0.50),
        (0.35, 0.35),
        (0.65, 0.35),
        (0.40, 0.65),
        (0.70, 0.60),
    ]
    pts: list[tuple[float, float]] = []
    for e, c in anchors:
        if len(pts) >= variants:
            break
        if exag_min <= e <= exag_max and cfg_min <= c <= cfg_max:
            pts.append((e, c))
    while len(pts) < variants:
        pts.append((
            rng.uniform(exag_min, exag_max),
            rng.uniform(cfg_min, cfg_max),
        ))
    rng.shuffle(pts)
    return pts[:variants]


def collect_data(args) -> None:
    rng = random.Random(args.random_seed)
    corpus = read_corpus(args.corpus, max_chars=args.max_chars) if args.corpus else []

    texts: list[str] = []
    if corpus:
        rng.shuffle(corpus)
        texts.extend(corpus[: args.texts])

    seen = {normalize_key(x) for x in texts}
    attempts = 0
    while len(texts) < args.texts and attempts < args.texts * 30:
        attempts += 1
        t = synthetic_text(rng, args.min_words, args.max_words)
        k = normalize_key(t)
        if k not in seen:
            seen.add(k)
            texts.append(t)

    if len(texts) < args.texts:
        raise RuntimeError(f"Could only create {len(texts)} unique texts.")

    print(f"Loading Chatterbox on {args.device} ...", flush=True)
    probe = ChatterboxTokenProbe(device=args.device, voice_ref=args.voice_ref)
    print(
        f"Collecting {len(texts)} texts × {args.variants_per_text} variants "
        f"= {len(texts) * args.variants_per_text} labels",
        flush=True,
    )

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    exists = out.exists() and out.stat().st_size > 0
    mode = "a" if args.append else "w"

    with out.open(mode, encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=DATA_FIELDS)
        if mode == "w" or not exists:
            writer.writeheader()

        n = 0
        t0 = time.time()
        waveform_checks = 0
        for ti, text in enumerate(texts):
            text_id = normalize_key(text)
            cps = _control_points(
                rng,
                args.variants_per_text,
                args.exag_min,
                args.exag_max,
                args.cfg_min,
                args.cfg_max,
            )

            for vi, (exag, cfg) in enumerate(cps):
                if args.seed_mode == "fixed":
                    seed = args.tts_seed
                else:
                    seed = args.tts_seed + ti * 1009 + vi * 97

                tokens = probe.probe_tokens(
                    text=text,
                    exaggeration=exag,
                    cfg_weight=cfg,
                    temperature=args.temperature,
                    repetition_penalty=args.repetition_penalty,
                    min_p=args.min_p,
                    top_p=args.top_p,
                    seed=seed,
                    max_new_tokens=args.max_new_tokens,
                )
                token_count = int(tokens.numel())
                duration = token_count / float(probe.token_rate)

                wav_duration = ""
                wav_error = ""
                if args.waveform_check_rate > 0 and rng.random() < args.waveform_check_rate:
                    wd = probe.waveform_duration_from_tokens(tokens)
                    waveform_checks += 1
                    wav_duration = f"{wd:.9f}"
                    wav_error = f"{100.0 * abs(wd - duration) / max(1e-9, wd):.6f}"

                writer.writerow({
                    "text_id": text_id,
                    "text": text,
                    "exaggeration": f"{exag:.6f}",
                    "cfg_weight": f"{cfg:.6f}",
                    "seed": seed,
                    "temperature": args.temperature,
                    "repetition_penalty": args.repetition_penalty,
                    "min_p": args.min_p,
                    "top_p": args.top_p,
                    "speech_tokens": token_count,
                    "token_rate": probe.token_rate,
                    "duration_s": f"{duration:.9f}",
                    "waveform_duration_s": wav_duration,
                    "waveform_error_pct": wav_error,
                })
                f.flush()
                n += 1
                if n % 25 == 0:
                    elapsed = time.time() - t0
                    rate = n / max(1e-6, elapsed)
                    print(
                        f"  {n}/{len(texts) * args.variants_per_text} "
                        f"({rate:.2f} labels/s)",
                        flush=True,
                    )

    print(f"Wrote {n} labels to {out}")
    if waveform_checks:
        print(f"Performed {waveform_checks} token→waveform duration checks.")
    probe.close()


# ---------------------------------------------------------------------------
# Learned ensemble
# ---------------------------------------------------------------------------

@dataclass
class Record:
    text_id: str
    text: str
    exaggeration: float
    cfg_weight: float
    speech_tokens: float
    duration_s: float


def load_records(path: str | Path) -> list[Record]:
    records: list[Record] = []
    with Path(path).open("r", encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f):
            records.append(Record(
                text_id=row.get("text_id") or normalize_key(row["text"]),
                text=row["text"],
                exaggeration=float(row["exaggeration"]),
                cfg_weight=float(row["cfg_weight"]),
                speech_tokens=float(row["speech_tokens"]),
                duration_s=float(row["duration_s"]),
            ))
    if not records:
        raise ValueError("Dataset is empty.")
    return records


def regression_metrics(y_true_tokens: np.ndarray, y_pred_tokens: np.ndarray, token_rate: float = 25.0):
    y_true_tokens = np.asarray(y_true_tokens, dtype=float)
    y_pred_tokens = np.asarray(y_pred_tokens, dtype=float)
    true_s = y_true_tokens / token_rate
    pred_s = y_pred_tokens / token_rate
    err = pred_s - true_s
    ape = np.abs(err) / np.maximum(1e-9, true_s) * 100.0

    return {
        "n": int(len(y_true_tokens)),
        "mae_seconds": float(np.mean(np.abs(err))),
        "median_abs_seconds": float(np.median(np.abs(err))),
        "rmse_seconds": float(np.sqrt(np.mean(err ** 2))),
        "mape_percent": float(np.mean(ape)),
        "median_ape_percent": float(np.median(ape)),
        "p90_ape_percent": float(np.percentile(ape, 90)),
        "p95_ape_percent": float(np.percentile(ape, 95)),
        "p99_ape_percent": float(np.percentile(ape, 99)),
        "max_ape_percent": float(np.max(ape)),
        "within_1pct_percent": float(100.0 * np.mean(ape < 1.0)),
        "within_2pct_percent": float(100.0 * np.mean(ape < 2.0)),
        "within_5pct_percent": float(100.0 * np.mean(ape < 5.0)),
    }


class DurationEnsemble:
    """
    Ensemble:
      * sparse lexical Ridge: char + word TF-IDF + dense features
      * ExtraTrees on dense linguistic/control features
      * HistGradientBoosting on dense features
      * optional LightGBM on dense features

    Base models predict log(speech_token_count), then a tiny linear blender
    combines them.
    """

    def __init__(self, random_seed: int = 1234):
        self.random_seed = random_seed
        self.feature_names: list[str] = []
        self.char_vec = None
        self.word_vec = None
        self.scaler = None
        self.ridge = None
        self.extra = None
        self.hist = None
        self.lgbm = None
        self.model_names: list[str] = []
        self.blender_coef: Optional[np.ndarray] = None
        self.blender_intercept: float = 0.0
        self.token_rate: float = 25.0
        self.metadata: dict = {}

    def _dense_matrix(self, records: Sequence[Record], fit_names: bool = False) -> np.ndarray:
        dicts = [
            text_feature_dict(r.text, r.exaggeration, r.cfg_weight)
            for r in records
        ]
        if fit_names:
            self.feature_names = sorted(dicts[0].keys())
        return np.asarray(
            [[d.get(k, 0.0) for k in self.feature_names] for d in dicts],
            dtype=np.float32,
        )

    def _text_list(self, records: Sequence[Record]) -> list[str]:
        return [r.text for r in records]

    def fit_base(self, records: Sequence[Record], use_lightgbm: bool = True) -> None:
        from scipy.sparse import csr_matrix, hstack
        from sklearn.ensemble import ExtraTreesRegressor, HistGradientBoostingRegressor
        from sklearn.feature_extraction.text import TfidfVectorizer
        from sklearn.linear_model import Ridge
        from sklearn.preprocessing import StandardScaler

        y = np.log(np.maximum(1.0, np.asarray([r.speech_tokens for r in records], dtype=np.float64)))
        Xd = self._dense_matrix(records, fit_names=True)
        texts = self._text_list(records)

        min_df = 2 if len(records) >= 200 else 1
        self.char_vec = TfidfVectorizer(
            analyzer="char_wb",
            ngram_range=(2, 5),
            min_df=min_df,
            max_features=35000,
            sublinear_tf=True,
            dtype=np.float32,
        )
        self.word_vec = TfidfVectorizer(
            analyzer="word",
            ngram_range=(1, 2),
            min_df=min_df,
            max_features=18000,
            sublinear_tf=True,
            strip_accents="unicode",
            dtype=np.float32,
        )

        Xc = self.char_vec.fit_transform(texts)
        Xw = self.word_vec.fit_transform(texts)
        self.scaler = StandardScaler()
        Xds = self.scaler.fit_transform(Xd).astype(np.float32)
        Xs = hstack([Xc, Xw, csr_matrix(Xds)], format="csr")

        self.ridge = Ridge(alpha=4.0, solver="lsqr", tol=1e-5)
        self.ridge.fit(Xs, y)

        self.extra = ExtraTreesRegressor(
            n_estimators=600,
            min_samples_leaf=1,
            max_features=0.90,
            n_jobs=-1,
            random_state=self.random_seed,
        )
        self.extra.fit(Xd, y)

        self.hist = HistGradientBoostingRegressor(
            learning_rate=0.045,
            max_iter=500,
            max_leaf_nodes=31,
            l2_regularization=0.35,
            min_samples_leaf=max(8, min(25, len(records) // 80)),
            random_state=self.random_seed,
        )
        self.hist.fit(Xd, y)

        self.lgbm = None
        if use_lightgbm:
            try:
                from lightgbm import LGBMRegressor
                self.lgbm = LGBMRegressor(
                    objective="regression",
                    n_estimators=1200,
                    learning_rate=0.025,
                    num_leaves=31,
                    max_depth=-1,
                    min_child_samples=max(10, min(30, len(records) // 70)),
                    subsample=0.90,
                    colsample_bytree=0.90,
                    reg_alpha=0.05,
                    reg_lambda=0.50,
                    random_state=self.random_seed,
                    n_jobs=-1,
                    verbosity=-1,
                )
                self.lgbm.fit(Xd, y)
            except Exception as e:
                print(f"LightGBM unavailable; continuing without it: {e}", file=sys.stderr)
                self.lgbm = None

        self.model_names = ["ridge", "extra", "hist"]
        if self.lgbm is not None:
            self.model_names.append("lightgbm")

    def _matrices(self, records: Sequence[Record]):
        from scipy.sparse import csr_matrix, hstack
        Xd = self._dense_matrix(records, fit_names=False)
        texts = self._text_list(records)
        Xc = self.char_vec.transform(texts)
        Xw = self.word_vec.transform(texts)
        Xds = self.scaler.transform(Xd).astype(np.float32)
        Xs = hstack([Xc, Xw, csr_matrix(Xds)], format="csr")
        return Xd, Xs

    def base_predict_log(self, records: Sequence[Record]) -> np.ndarray:
        Xd, Xs = self._matrices(records)
        preds = [
            np.asarray(self.ridge.predict(Xs), dtype=float),
            np.asarray(self.extra.predict(Xd), dtype=float),
            np.asarray(self.hist.predict(Xd), dtype=float),
        ]
        if self.lgbm is not None:
            preds.append(np.asarray(self.lgbm.predict(Xd), dtype=float))
        return np.column_stack(preds)

    def fit_blender(self, calibration_records: Sequence[Record]) -> None:
        from sklearn.linear_model import LinearRegression
        P = self.base_predict_log(calibration_records)
        y = np.log(np.maximum(
            1.0,
            np.asarray([r.speech_tokens for r in calibration_records], dtype=float),
        ))
        blender = LinearRegression(positive=True)
        blender.fit(P, y)
        coef = np.asarray(blender.coef_, dtype=float)
        # Avoid a pathological all-zero positive solution.
        if not np.isfinite(coef).all() or coef.sum() <= 1e-8:
            coef = np.ones(P.shape[1], dtype=float) / P.shape[1]
            intercept = 0.0
        else:
            intercept = float(blender.intercept_)
        self.blender_coef = coef
        self.blender_intercept = intercept

    def set_blender(self, coef: np.ndarray, intercept: float) -> None:
        self.blender_coef = np.asarray(coef, dtype=float)
        self.blender_intercept = float(intercept)

    def predict_records_tokens(self, records: Sequence[Record]) -> np.ndarray:
        P = self.base_predict_log(records)
        if self.blender_coef is None:
            z = np.mean(P, axis=1)
        else:
            # In case LightGBM availability changed between fitting objects,
            # use the overlapping predictors only and renormalize coefficients.
            n = min(P.shape[1], len(self.blender_coef))
            coef = self.blender_coef[:n].copy()
            if coef.sum() > 0:
                # Preserve relative weights; intercept remains from calibration.
                pass
            z = P[:, :n] @ coef + self.blender_intercept
        return np.maximum(1.0, np.exp(z))

    def predict_tokens(self, text: str, exaggeration: float, cfg_weight: float) -> float:
        rec = Record("", text, float(exaggeration), float(cfg_weight), 1.0, 0.04)
        return float(self.predict_records_tokens([rec])[0])

    def predict_seconds(self, text: str, exaggeration: float, cfg_weight: float) -> float:
        return self.predict_tokens(text, exaggeration, cfg_weight) / self.token_rate


def grouped_split(records: Sequence[Record], random_seed: int, test_size: float, cal_size: float):
    from sklearn.model_selection import GroupShuffleSplit

    idx = np.arange(len(records))
    groups = np.asarray([r.text_id for r in records])

    split1 = GroupShuffleSplit(
        n_splits=1, test_size=test_size, random_state=random_seed
    )
    traincal_idx, test_idx = next(split1.split(idx, groups=groups))

    # cal_size is a fraction of the full dataset.
    relative_cal = cal_size / max(1e-9, 1.0 - test_size)
    groups_traincal = groups[traincal_idx]
    split2 = GroupShuffleSplit(
        n_splits=1, test_size=relative_cal, random_state=random_seed + 1
    )
    train_rel, cal_rel = next(split2.split(traincal_idx, groups=groups_traincal))
    train_idx = traincal_idx[train_rel]
    cal_idx = traincal_idx[cal_rel]

    def take(indices):
        return [records[int(i)] for i in indices]

    return take(train_idx), take(cal_idx), take(test_idx)


def print_metrics(title: str, metrics: dict) -> None:
    print(f"\n{title}")
    print("-" * len(title))
    for k, v in metrics.items():
        if isinstance(v, float):
            print(f"{k:24s}: {v:.6f}")
        else:
            print(f"{k:24s}: {v}")


def train_model(args) -> None:
    import joblib

    records = load_records(args.data)
    if len({r.text_id for r in records}) < 30:
        raise ValueError(
            "Too few unique texts. Use at least ~100 unique texts; for high "
            "accuracy, use 1000+ domain-matched chunks."
        )

    train, cal, test = grouped_split(
        records,
        random_seed=args.random_seed,
        test_size=args.test_size,
        cal_size=args.cal_size,
    )

    print(
        f"Rows: train={len(train)}, calibration={len(cal)}, test={len(test)}\n"
        f"Unique texts: train={len({r.text_id for r in train})}, "
        f"cal={len({r.text_id for r in cal})}, "
        f"test={len({r.text_id for r in test})}"
    )

    eval_model = DurationEnsemble(random_seed=args.random_seed)
    print("Fitting base models...", flush=True)
    eval_model.fit_base(train, use_lightgbm=not args.no_lightgbm)
    print("Fitting ensemble blender on held-out calibration texts...", flush=True)
    eval_model.fit_blender(cal)

    y_test = np.asarray([r.speech_tokens for r in test], dtype=float)
    pred_test = eval_model.predict_records_tokens(test)
    metrics = regression_metrics(y_test, pred_test, token_rate=25.0)
    print_metrics("HELD-OUT GROUPED TEST METRICS", metrics)

    # Duration buckets reveal whether short clips are causing large relative errors.
    durations = y_test / 25.0
    buckets = [
        (0, 3), (3, 6), (6, 12), (12, 20), (20, 40), (40, float("inf"))
    ]
    for lo, hi in buckets:
        mask = (durations >= lo) & (durations < hi)
        if mask.sum() >= 5:
            name = f"{lo:g}–{'∞' if math.isinf(hi) else f'{hi:g}'} sec"
            print_metrics(
                f"TEST BUCKET {name}",
                regression_metrics(y_test[mask], pred_test[mask], 25.0),
            )

    # Production model gets train + calibration; test remains untouched.
    production_records = train + cal
    final_model = DurationEnsemble(random_seed=args.random_seed)
    print("\nRefitting production base models on train + calibration...", flush=True)
    final_model.fit_base(production_records, use_lightgbm=not args.no_lightgbm)
    final_model.set_blender(
        eval_model.blender_coef.copy(),
        eval_model.blender_intercept,
    )
    final_model.metadata = {
        "created_unix": time.time(),
        "training_rows": len(production_records),
        "heldout_rows": len(test),
        "unique_training_texts": len({r.text_id for r in production_records}),
        "test_metrics": metrics,
        "target": "Chatterbox T3 speech-token count",
        "token_rate_hz": 25.0,
        "notes": (
            "Pure learned predictions are not guaranteed <1% for every utterance. "
            "Use ChatterboxTokenProbe for final frame-level timing."
        ),
    }

    out = Path(args.model)
    out.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(final_model, out, compress=3)
    print(f"\nSaved: {out}")

    if args.require_mape is not None and metrics["mape_percent"] > args.require_mape:
        raise SystemExit(
            f"Validation MAPE {metrics['mape_percent']:.3f}% exceeds "
            f"required {args.require_mape:.3f}%."
        )
    if args.require_max_ape is not None and metrics["max_ape_percent"] > args.require_max_ape:
        raise SystemExit(
            f"Validation max APE {metrics['max_ape_percent']:.3f}% exceeds "
            f"required {args.require_max_ape:.3f}%."
        )


# ---------------------------------------------------------------------------
# Persistent predictor adapter
# ---------------------------------------------------------------------------

_CACHED_MODEL_PATH: Optional[str] = None
_CACHED_MODEL: Optional[DurationEnsemble] = None


def load_duration_model(path: str | Path) -> DurationEnsemble:
    import joblib
    model = joblib.load(str(path))
    if not isinstance(model, DurationEnsemble):
        raise TypeError(f"{path} does not contain a DurationEnsemble.")
    return model


def estimate_duration(
    text: str,
    exaggeration: float,
    cfg_weight: float,
) -> float:
    """
    Drop-in adapter for safety_montage_narrator.py.

    Configure:
        export CHATTERBOX_DURATION_MODEL=/path/duration_model.joblib
    """
    global _CACHED_MODEL_PATH, _CACHED_MODEL
    path = os.environ.get("CHATTERBOX_DURATION_MODEL")
    if not path:
        # Graceful fallback makes the function importable before training.
        return heuristic_duration(text, exaggeration, cfg_weight)

    path = str(Path(path).expanduser().resolve())
    if _CACHED_MODEL is None or _CACHED_MODEL_PATH != path:
        _CACHED_MODEL = load_duration_model(path)
        _CACHED_MODEL_PATH = path
    return _CACHED_MODEL.predict_seconds(text, exaggeration, cfg_weight)


# ---------------------------------------------------------------------------
# Prediction / benchmarking / parameter search
# ---------------------------------------------------------------------------

def cmd_predict(args) -> None:
    model = load_duration_model(args.model)
    text = Path(args.text_file).read_text(encoding="utf-8") if args.text_file else args.text
    chunks = hard_wrap(text, args.max_chars)
    pred_chunks = [
        model.predict_seconds(c, args.exaggeration, args.cfg_weight)
        for c in chunks
    ]
    total = sum(pred_chunks) + args.inter_chunk_pause * max(0, len(chunks) - 1)

    print(f"chunks              : {len(chunks)}")
    for i, sec in enumerate(pred_chunks, 1):
        print(f"chunk_{i:02d}_seconds    : {sec:.6f}")
    print(f"predicted_seconds   : {total:.6f}")
    print(f"exaggeration        : {args.exaggeration:.4f}")
    print(f"cfg_weight          : {args.cfg_weight:.4f}")


def cmd_probe(args) -> None:
    import torch
    text = Path(args.text_file).read_text(encoding="utf-8") if args.text_file else args.text
    chunks = hard_wrap(text, args.max_chars)
    probe = ChatterboxTokenProbe(device=args.device, voice_ref=args.voice_ref)

    total = 0.0
    saved = []
    for i, chunk in enumerate(chunks):
        seed = args.seed + i
        toks = probe.probe_tokens(
            chunk,
            exaggeration=args.exaggeration,
            cfg_weight=args.cfg_weight,
            temperature=args.temperature,
            repetition_penalty=args.repetition_penalty,
            min_p=args.min_p,
            top_p=args.top_p,
            seed=seed,
            max_new_tokens=args.max_new_tokens,
        )
        sec = probe.token_duration_seconds(toks)
        total += sec
        print(
            f"chunk {i+1}: tokens={int(toks.numel())}, "
            f"duration={sec:.6f}s, seed={seed}"
        )
        if args.verify_waveform:
            wav_sec = probe.waveform_duration_from_tokens(toks)
            err = 100.0 * abs(wav_sec - sec) / max(wav_sec, 1e-9)
            print(f"          waveform={wav_sec:.6f}s, token-map error={err:.6f}%")
        saved.append(toks.detach().cpu())

    total += args.inter_chunk_pause * max(0, len(chunks) - 1)
    print(f"probe_total_seconds : {total:.6f}")

    if args.save_tokens:
        # A list is intentional because long narration is synthesized in chunks.
        torch.save(saved, args.save_tokens)
        print(f"saved token sequences to: {args.save_tokens}")
    probe.close()


def cmd_benchmark(args) -> None:
    model = load_duration_model(args.model)
    records = load_records(args.data)
    y = np.asarray([r.speech_tokens for r in records], dtype=float)
    p = model.predict_records_tokens(records)
    print_metrics("DATASET METRICS", regression_metrics(y, p, 25.0))


def cmd_search(args) -> None:
    model = load_duration_model(args.model)
    text = Path(args.text_file).read_text(encoding="utf-8") if args.text_file else args.text
    chunks = hard_wrap(text, args.max_chars)

    rows = []
    e = args.exag_min
    while e <= args.exag_max + 1e-9:
        c = args.cfg_min
        while c <= args.cfg_max + 1e-9:
            sec = sum(model.predict_seconds(x, e, c) for x in chunks)
            sec += args.inter_chunk_pause * max(0, len(chunks) - 1)
            err = abs(sec - args.target)
            # Small naturalness regularizer around 0.5/0.5.
            prior = ((e - 0.5) / 0.2) ** 2 + ((c - 0.5) / 0.2) ** 2
            score = err + args.naturalness_weight * prior
            rows.append((score, err, sec, e, c))
            c += args.step
        e += args.step

    rows.sort()
    for rank, (score, err, sec, e, c) in enumerate(rows[: args.top], 1):
        print(
            f"{rank:2d}. exag={e:.3f} cfg={c:.3f} "
            f"duration={sec:.4f}s abs_error={err:.4f}s score={score:.4f}"
        )



def cmd_synthesize_tokens(args) -> None:
    """
    Decode speech-token sequences saved by `probe --save-tokens`.

    This is the strongest timing mode: T3 is NOT re-run, so the waveform is
    decoded from exactly the token sequence whose duration was measured.
    """
    import torch
    import torchaudio as ta

    probe = ChatterboxTokenProbe(device=args.device, voice_ref=args.voice_ref)
    sequences = torch.load(args.tokens, map_location="cpu", weights_only=True)
    if torch.is_tensor(sequences):
        sequences = [sequences]
    if not isinstance(sequences, (list, tuple)) or not sequences:
        raise ValueError("Token file must contain one tensor or a non-empty list of tensors.")

    sr = int(probe.model.sr)
    silence = torch.zeros(
        (1, max(1, round(sr * args.inter_chunk_pause))),
        dtype=torch.float32,
    )
    waves = []
    token_seconds = 0.0

    for i, seq in enumerate(sequences):
        seq = torch.as_tensor(seq, dtype=torch.long, device=probe.model.device).reshape(-1)
        token_seconds += probe.token_duration_seconds(seq)

        with torch.inference_mode():
            wav, _ = probe.model.s3gen.inference(
                speech_tokens=seq,
                ref_dict=probe.model.conds.gen,
            )

        wav_np = wav.squeeze(0).detach().float().cpu().numpy()
        if not args.no_watermark:
            wav_np = probe.model.watermarker.apply_watermark(wav_np, sample_rate=sr)
        wav_t = torch.from_numpy(np.asarray(wav_np, dtype=np.float32)).reshape(1, -1)
        waves.append(wav_t)

        if i != len(sequences) - 1:
            waves.append(silence.clone())

    full = torch.cat(waves, dim=-1)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    ta.save(str(out), full, sr)

    actual_seconds = full.shape[-1] / float(sr)
    expected_seconds = (
        token_seconds
        + args.inter_chunk_pause * max(0, len(sequences) - 1)
    )
    ape = 100.0 * abs(actual_seconds - expected_seconds) / max(1e-9, actual_seconds)

    print(f"chunks                    : {len(sequences)}")
    print(f"token_predicted_seconds   : {expected_seconds:.9f}")
    print(f"waveform_actual_seconds   : {actual_seconds:.9f}")
    print(f"absolute_error_seconds    : {abs(actual_seconds - expected_seconds):.9f}")
    print(f"absolute_percent_error    : {ape:.9f}")
    print(f"output                    : {out}")
    probe.close()

# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="High-accuracy Chatterbox TTS duration estimator."
    )
    sub = p.add_subparsers(dest="command", required=True)

    c = sub.add_parser("collect", help="Generate T3 labels from Chatterbox.")
    c.add_argument("--voice-ref", required=True)
    c.add_argument("--corpus", action="append", default=[])
    c.add_argument("--out", default="duration_data.csv")
    c.add_argument("--texts", type=int, default=1500)
    c.add_argument("--variants-per-text", type=int, default=5)
    c.add_argument("--max-chars", type=int, default=280)
    c.add_argument("--min-words", type=int, default=8)
    c.add_argument("--max-words", type=int, default=55)
    c.add_argument("--exag-min", type=float, default=0.30)
    c.add_argument("--exag-max", type=float, default=0.82)
    c.add_argument("--cfg-min", type=float, default=0.25)
    c.add_argument("--cfg-max", type=float, default=0.75)
    c.add_argument("--temperature", type=float, default=0.8)
    c.add_argument("--repetition-penalty", type=float, default=1.2)
    c.add_argument("--min-p", type=float, default=0.05)
    c.add_argument("--top-p", type=float, default=1.0)
    c.add_argument("--tts-seed", type=int, default=1234)
    c.add_argument("--seed-mode", choices=["fixed", "vary"], default="vary")
    c.add_argument("--random-seed", type=int, default=1234)
    c.add_argument("--max-new-tokens", type=int, default=1000)
    c.add_argument(
        "--waveform-check-rate",
        type=float,
        default=0.02,
        help="Fraction of labels also decoded through S3Gen to verify token→seconds mapping.",
    )
    c.add_argument("--device", default="cuda")
    c.add_argument("--append", action="store_true")
    c.set_defaults(func=collect_data)

    t = sub.add_parser("train", help="Train and honestly evaluate the estimator.")
    t.add_argument("--data", required=True)
    t.add_argument("--model", default="duration_model.joblib")
    t.add_argument("--random-seed", type=int, default=1234)
    t.add_argument("--test-size", type=float, default=0.15)
    t.add_argument("--cal-size", type=float, default=0.15)
    t.add_argument("--no-lightgbm", action="store_true")
    t.add_argument(
        "--require-mape",
        type=float,
        default=None,
        help="Exit nonzero if grouped held-out MAPE exceeds this percent.",
    )
    t.add_argument(
        "--require-max-ape",
        type=float,
        default=None,
        help="Exit nonzero if ANY grouped held-out example exceeds this percent.",
    )
    t.set_defaults(func=train_model)

    q = sub.add_parser("predict", help="Fast learned prediction.")
    q.add_argument("--model", required=True)
    g = q.add_mutually_exclusive_group(required=True)
    g.add_argument("--text")
    g.add_argument("--text-file")
    q.add_argument("--exaggeration", type=float, default=0.5)
    q.add_argument("--cfg-weight", type=float, default=0.5)
    q.add_argument("--max-chars", type=int, default=280)
    q.add_argument("--inter-chunk-pause", type=float, default=0.08)
    q.set_defaults(func=cmd_predict)

    r = sub.add_parser("probe", help="T3-only near-exact duration probe.")
    r.add_argument("--voice-ref", required=True)
    g = r.add_mutually_exclusive_group(required=True)
    g.add_argument("--text")
    g.add_argument("--text-file")
    r.add_argument("--exaggeration", type=float, default=0.5)
    r.add_argument("--cfg-weight", type=float, default=0.5)
    r.add_argument("--temperature", type=float, default=0.8)
    r.add_argument("--repetition-penalty", type=float, default=1.2)
    r.add_argument("--min-p", type=float, default=0.05)
    r.add_argument("--top-p", type=float, default=1.0)
    r.add_argument("--seed", type=int, default=1234)
    r.add_argument("--max-new-tokens", type=int, default=1000)
    r.add_argument("--max-chars", type=int, default=280)
    r.add_argument("--inter-chunk-pause", type=float, default=0.08)
    r.add_argument("--device", default="cuda")
    r.add_argument("--verify-waveform", action="store_true")
    r.add_argument("--save-tokens")
    r.set_defaults(func=cmd_probe)

    st = sub.add_parser(
        "synthesize-tokens",
        help="Decode tokens saved by probe without re-running stochastic T3.",
    )
    st.add_argument("--voice-ref", required=True)
    st.add_argument("--tokens", required=True)
    st.add_argument("--out", default="from_probed_tokens.wav")
    st.add_argument("--inter-chunk-pause", type=float, default=0.08)
    st.add_argument("--device", default="cuda")
    st.add_argument("--no-watermark", action="store_true")
    st.set_defaults(func=cmd_synthesize_tokens)

    b = sub.add_parser("benchmark", help="Evaluate a saved model on a CSV.")
    b.add_argument("--model", required=True)
    b.add_argument("--data", required=True)
    b.set_defaults(func=cmd_benchmark)

    s = sub.add_parser("search", help="Fast exag/CFG grid search for target duration.")
    s.add_argument("--model", required=True)
    g = s.add_mutually_exclusive_group(required=True)
    g.add_argument("--text")
    g.add_argument("--text-file")
    s.add_argument("--target", type=float, required=True)
    s.add_argument("--exag-min", type=float, default=0.30)
    s.add_argument("--exag-max", type=float, default=0.82)
    s.add_argument("--cfg-min", type=float, default=0.25)
    s.add_argument("--cfg-max", type=float, default=0.75)
    s.add_argument("--step", type=float, default=0.02)
    s.add_argument("--top", type=int, default=10)
    s.add_argument("--naturalness-weight", type=float, default=0.02)
    s.add_argument("--max-chars", type=int, default=280)
    s.add_argument("--inter-chunk-pause", type=float, default=0.08)
    s.set_defaults(func=cmd_search)

    return p


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
