"""Explain the actual pre-synthesis length contracts, with no model imports."""

ALGORITHM_FUNCTIONS = {
    "kokoro": ["plan_one", "plan_text", "synthesize"],
    "f5": ["build_plan", "main"],
    "emotivoice": ["apply_duration_controls", "vocoder_samples", "plan", "synthesize"],
    "styletts2": ["build_plans", "generate_chunk", "main"],
    "omnivoice": ["make_plan", "main"],
    "supertonic": ["plan", "synthesize", "validate_decoder"],
}

GUIDE_MARKDOWN = r'''
## Where the duration estimate happens, and why it matches exactly

**The requested passage's waveform is not generated first.** Each adapter
computes a length plan, prints/saves its preview, and then enters waveform
synthesis using that same plan. The notebook later reads the actual WAV header
independently for its comparison. A final report is produced after generation,
but the reported planned sample count was already computed before it.

The experiment is therefore testing a **reused synthesis-length contract**.
It is not testing an independent words-per-minute predictor against an arbitrary
unconstrained TTS call. Exact sample-count equality is a consequence of controlling
the lengths accepted by these decoders. “100%” here means zero measured duration
error in successful exports, not 100% accuracy of pronunciation, word completeness,
natural pacing, or arbitrary future versions. A failed length contract is reported
as an error; the scripts do not quietly rescale speech to make the score look good.

### The six algorithms

| Model | Computation before requested waveform synthesis | Frozen data reused by synthesis | Native chunk length |
|---|---|---|---|
| Kokoro | G2P → text/BERT encodings → voice-conditioned duration network. Sum sigmoid duration logits per phoneme; divide by speed, round, clamp to at least one duration unit | Integer phoneme durations, duration encodings, tokens, selected voice embedding | `600 * sum(durations)` samples at 24 kHz |
| F5-TTS | Reference-duration/text-byte ratio or your explicit seconds → allocate mel frames; include reference/STFT/text-token minimum clamps. This is an allocation heuristic, not a learned natural-duration forecast | Exact total flow frame count and reference-slice count for every chunk | `256 * (allocated_total_frames - floor(reference_samples/256) - 1)` samples at 24 kHz |
| EmotiVoice | G2P + text/speaker/style encodings → learned duration predictor → speed and phoneme-emphasis scaling → integer rounding/minimum lexical-phone guard | Integer durations, conditioned phoneme embeddings, pitch/energy factors | Analytic HiFiGAN convolution/transpose-convolution propagation from `sum(durations)` acoustic frames, at 16 kHz |
| StyleTTS2 | Phonemize/BERT encode → sample latent style separately for every take/chunk → reference/style blend → learned phoneme duration network → speed/rounding/minimum | Sampled acoustic/prosodic styles, integer durations, duration embeddings, seeds | `600 * sum(durations) - tail_trim_samples` samples at 24 kHz; default fixed trim 50 |
| OmniVoice | Pinned Unicode/text rule and reference token/text ratio (or default rate), short-text adjustment, speed and chunk limits; optional explicit seconds select a total token budget | Exact audio-token count for every chunk | `960 * target_tokens` samples at 24 kHz; token rate 25 Hz, i.e. 40 ms per token |
| Supertonic 3 | ONNX duration predictor conditioned on text and voice DP style → divide predicted seconds by speed → use SDK float32 conversion to integer samples and latent-frame allocation | Predicted duration, exact integer sample count, latent-frame count, IDs/masks | `int64(float32_duration * 44100)` samples after removing only precomputed latent-allocation padding |

**Kokoro:** durations are generated by the actual loaded model/voice combination,
not fitted from word count. The decoder's verified temporal geometry emits 600
samples per duration unit. Pitch/noise prediction and waveform decoding follow
the preview. Decoder noise may change audio between seeds without changing the
already frozen duration vector.

**F5:** let `R=floor(reference_samples/256)`, `B` be the reference transcript's
UTF-8 byte length, and `b` be the chunk's byte length. Without explicit seconds,
the requested total frames are `R + int(R*b/(B*speed))`. With explicit seconds,
the requested generated allocation is distributed by chunk byte lengths. The
adapter then applies the pinned flow's text/reference minimum and maximum
clamps. The preview uses this final allocation, not the raw requested seconds.
The flow is called with that exact `duration`; the reference region is excluded
and centered Vocos STFT geometry gives the sample formula in the table. F5 can
preview before loading the generator/vocoder weights, but still needs source
utilities, a reference waveform, vocabulary, and tokenization.

**EmotiVoice:** its duration predictor is conditioned on the learned speaker
identity, prompt/style embedding, and content. Durations are rounded after
speed/emphasis scaling. Spoken phonemes obey `min_phoneme_frames`, while pause
tokens may retain zero. The acoustic length regulator receives those exact
durations rather than recomputing them. Output lengths are propagated using
`Conv1d: floor((L+2p-d*(k-1)-1)/s)+1` and
`ConvTranspose1d: (L-1)*s-2p+d*(k-1)+output_padding+1`; residual blocks are checked
to preserve length. This computes sample count without running the vocoder.

**StyleTTS2:** stochastic style generation occurs **during planning**, before
duration prediction. Consequently each seed/take has its own preview. The
cached style and durations are reused by the later F0/energy/waveform path;
there is no second independent duration draw. This preflight does meaningful
neural computation and is not universally near-instant. A matching saved
`reuse_plan` can skip style/duration inference, subject to the documented cache
constraints.

**Omni:** the rule estimator chooses token lengths using Unicode-weighted text
and a reference-rate heuristic. The iterative acoustic-token generator is given
those exact target lengths; its codec produces 960 samples per token. Explicit
`duration` becomes `max(1, floor(seconds*25))` total tokens, apportioned across
chunks with exact integer allocation. The text heuristic can choose an unsuitable
speaking pace, but the resulting WAV still has the chosen length. This makes
allocation previews fast; it does not make the heuristic a <1% predictor of
unconstrained natural speech duration. Automatic silence removal, padding, and
upstream automatic chunking are disabled in this adapter.

**Supertonic:** only the duration graph handles the passage during planning.
The SDK allocates `ceil(samples/3072)` latent frames, each decoding to 3072
samples. It exports the precomputed sample count by removing the known final
allocation padding. This is an explicit native mechanism, not audio-content
silence detection. During **cold engine initialization**, the adapter does run
two tiny zero-latent vocoder probes to check this geometry, plus a duration-only
warm-up. Those probes are not synthesized versions of your passage and are
included in startup cost rather than warmed preview latency.

### Joins and exported sample rate

After planning all chunks, let `N_native` be their total samples, plus configured
pauses and minus actual configured F5/Style overlaps. The adapter calculates
the rational polyphase resampler length by integer ceiling:

```text
N_export = ceil(N_native * export_rate / native_rate)
planned_seconds = N_export / export_rate
actual_seconds = WAV_header_frames / WAV_header_sample_rate
benchmark_error_percent = 100 * abs(actual_seconds - planned_seconds) / actual_seconds
```

Native punctuation/BOS/EOS silence is already part of the generated chunk's
allocated length. Tiny edge fades, gain, and peak protection do not add or
remove samples. Style's fixed end correction and Super's predetermined latent
padding removal are disclosed and included before export-length calculation.
No successful recording is padded, time-stretched, or content-trimmed afterward
to conceal a mismatch. Fixed decoding corrections and requested crossfades are
different from estimating duration by measuring the completed recording.

### Where to inspect the evidence

The ZIP includes the complete Python adapters under `source/`, and each job's
`config.json`, text, preview/manifest, and `generation.log` under `job_details/`.
The catalog explorer also shows exact file/function line locations for planning
and synthesis. In the notebook, look for the worker's **Duration preflight**,
**Style/duration preflight**, or printed **preflight/Duration preview** message
before its generation progress starts.

| Adapter | Preview saved before requested waveform synthesis |
|---|---|
| Kokoro | Per-run `preview.json`, including integer durations and predicted export samples |
| F5 | Initial `manifest.json` with `preview` and `plan`, written before `load_models` and flow/vocoder synthesis |
| EmotiVoice | Initial `emotivoice_manifest.json` with phoneme durations and predicted samples, before `engine.synthesize` |
| StyleTTS2 | `duration_plan.pt` and initial `manifest.json` with per-take previews, before `generate_chunk` |
| OmniVoice | `estimate.json` with `plan`, before model loading/token generation in the normal design path |
| Supertonic | Initial `supertonic_manifest.json`, before passage text encoding/flow/vocoder generation |

Manifests that also contain output rows are updated after takes complete. Their
final modification times alone do not prove the original preview was computed
late; inspect the call order and generation logs. Kokoro's separate preview and
Omni's estimate file preserve standalone plan artifacts. The notebook's report
cell reads these already calculated quantities and independently measures WAV
headers; it does not derive planned duration from those headers.

Model loading, downloads, reference preparation, duration planning, waveform
synthesis, and independent ASR are distinct stages. A no-reference default may
first generate a **separate synthetic speaker-reference recording** on CPU; that
is not pre-generating the requested benchmark passages. The reported planning
latency is model-specific and excludes several cold-start costs. The 500-word
CPU Kokoro preview observed locally was several seconds, so exactness should
not be confused with a universal near-instant performance guarantee.
'''
