"""Audited OmniVoice voice and configuration reference for the Kaggle notebook.

This authoring module contains documentation/data only; no model imports or I/O.
The catalog is frozen to the source and weight revisions used by the adapters.
"""

import json

SOURCE_COMMIT = "08be0b4ccbac3e13e374e86fbfead4b4cac343e2"
SOURCE_BASE = f"https://github.com/k2-fsa/OmniVoice/blob/{SOURCE_COMMIT}"

VOICE_CATALOG = {
    "model": "omnivoice",
    "source_commit": SOURCE_COMMIT,
    "model_id": "k2-fsa/OmniVoice",
    "model_revision": "c5fdb5ccb189668d56333f77ba2629f4cd7535f4",
    "arbitrary_reference_audio": True,
    "reference_transcript_required_by_adapter": True,
    "reference_recommendation_seconds": [3, 10],
    "notebook_shared_reference_seconds": [1, 8],
    "preset_speaker_ids": [],
    "voice_design": {
        "gender": {"male": "男", "female": "女"},
        "age": {
            "child": "儿童",
            "teenager": "少年",
            "young adult": "青年",
            "middle-aged": "中年",
            "elderly": "老年",
        },
        "pitch": {
            "very low pitch": "极低音调",
            "low pitch": "低音调",
            "moderate pitch": "中音调",
            "high pitch": "高音调",
            "very high pitch": "极高音调",
        },
        "style": {"whisper": "耳语"},
        "english_accent": [
            "american accent", "british accent", "australian accent", "chinese accent",
            "canadian accent", "indian accent", "korean accent", "portuguese accent",
            "russian accent", "japanese accent",
        ],
        "chinese_dialect": [
            "河南话", "陕西话", "四川话", "贵州话", "云南话", "桂林话",
            "济南话", "石家庄话", "甘肃话", "宁夏话", "青岛话", "东北话",
        ],
    },
    "emotion_labels": [],
    "nonverbal_text_tags": [
        "[laughter]", "[sigh]", "[confirmation-en]", "[question-en]",
        "[question-ah]", "[question-oh]", "[question-ei]", "[question-yi]",
        "[surprise-ah]", "[surprise-oh]", "[surprise-wa]", "[surprise-yo]",
        "[dissatisfaction-hnn]",
    ],
    "language_name_to_id": json.loads(r'''{
    "abadi": "kbt",
    "abkhazian": "ab",
    "abron": "abr",
    "abua": "abn",
    "adamawa fulfulde": "fub",
    "adyghe": "ady",
    "afade": "aal",
    "afrikaans": "af",
    "agwagwune": "yay",
    "aja (benin)": "ajg",
    "akebu": "keu",
    "alago": "ala",
    "albanian": "sq",
    "algerian arabic": "arq",
    "algerian saharan arabic": "aao",
    "ambo-pasco quechua": "qva",
    "ambonese malay": "abs",
    "amdo tibetan": "adx",
    "amharic": "am",
    "anaang": "anw",
    "angika": "anp",
    "antankarana malagasy": "xmv",
    "aragonese": "an",
    "arbëreshë albanian": "aae",
    "arequipa-la unión quechua": "qxu",
    "armenian": "hy",
    "ashe": "ahs",
    "ashéninka perené": "prq",
    "askopan": "eiv",
    "assamese": "as",
    "asturian": "ast",
    "atayal": "tay",
    "awak": "awo",
    "ayacucho quechua": "quy",
    "azerbaijani": "az",
    "baatonum": "bba",
    "bacama": "bcy",
    "bade": "bde",
    "bafia": "ksf",
    "bafut": "bfd",
    "bagirmi fulfulde": "fui",
    "bago-kusuntu": "bqg",
    "baharna arabic": "abv",
    "bakoko": "bkh",
    "balanta-ganja": "bjt",
    "balti": "bft",
    "bamenyam": "bce",
    "bamun": "bax",
    "bangwinji": "bsj",
    "banjar": "bjn",
    "bankon": "abb",
    "baoulé": "bci",
    "bara malagasy": "bhr",
    "barok": "bjk",
    "basa (cameroon)": "bas",
    "basa (nigeria)": "bzw",
    "bashkir": "ba",
    "basque": "eu",
    "batak mandailing": "btm",
    "batanga": "bnm",
    "bateri": "btv",
    "bats": "bbl",
    "bayot": "bda",
    "bebele": "beb",
    "belarusian": "be",
    "bengali": "bn",
    "betawi": "bew",
    "bhili": "bhb",
    "bhojpuri": "bho",
    "bilur": "bxf",
    "bima": "bhp",
    "bodo": "brx",
    "boghom": "bux",
    "bokyi": "bky",
    "bomu": "bmq",
    "bondei": "bou",
    "borgu fulfulde": "fue",
    "bosnian": "bs",
    "brahui": "brh",
    "braj": "bra",
    "breton": "br",
    "buduma": "bdm",
    "buginese": "bug",
    "bukharic": "bhh",
    "bulgarian": "bg",
    "bulu (cameroon)": "bum",
    "bundeli": "bns",
    "bunun": "bnn",
    "bura-pabir": "bwr",
    "burak": "bys",
    "burmese": "my",
    "burushaski": "bsk",
    "cacaloxtepec mixtec": "miu",
    "cajatambo north lima quechua": "qvl",
    "cakfem-mushere": "cky",
    "cameroon pidgin": "wes",
    "campidanese sardinian": "sro",
    "cantonese": "yue",
    "catalan": "ca",
    "cebuano": "ceb",
    "cen": "cen",
    "central kurdish": "ckb",
    "central nahuatl": "nhn",
    "central pame": "pbs",
    "central pashto": "pst",
    "central puebla nahuatl": "ncx",
    "central tarahumara": "tar",
    "central yupik": "esu",
    "central-eastern niger fulfulde": "fuq",
    "chadian arabic": "shu",
    "chichewa": "ny",
    "chichicapan zapotec": "zpv",
    "chiga": "cgg",
    "chimalapa zoque": "zoh",
    "chimborazo highland quichua": "qug",
    "chinese": "zh",
    "chiquián ancash quechua": "qxa",
    "chitwania tharu": "the",
    "chokwe": "cjk",
    "chuvash": "cv",
    "cibak": "ckl",
    "coastal konjo": "kjc",
    "copainalá zoque": "zoc",
    "cornish": "kw",
    "corongo ancash quechua": "qwa",
    "croatian": "hr",
    "cross river mbembe": "mfn",
    "cuyamecalco mixtec": "xtu",
    "czech": "cs",
    "dadiya": "dbd",
    "dagbani": "dag",
    "dameli": "dml",
    "danish": "da",
    "dargwa": "dar",
    "dazaga": "dzg",
    "deccan": "dcc",
    "degema": "deg",
    "dera (nigeria)": "kna",
    "dghwede": "dgh",
    "dhatki": "mki",
    "dhivehi": "dv",
    "dhofari arabic": "adf",
    "dijim-bwilim": "cfa",
    "dogri": "dgo",
    "domaaki": "dmk",
    "dotyali": "dty",
    "duala": "dua",
    "dutch": "nl",
    "dũya": "ldb",
    "dyula": "dyu",
    "eastern balochi": "bgp",
    "eastern bolivian guaraní": "gui",
    "eastern egyptian bedawi arabic": "avl",
    "eastern krahn": "kqo",
    "eastern mari": "mhr",
    "eastern yiddish": "ydd",
    "ebrié": "ebr",
    "eggon": "ego",
    "egyptian arabic": "arz",
    "ejagham": "etu",
    "eleme": "elm",
    "eloyi": "afo",
    "embu": "ebu",
    "english": "en",
    "erzya": "myv",
    "esan": "ish",
    "esperanto": "eo",
    "estonian": "et",
    "eton (cameroon)": "eto",
    "ewondo": "ewo",
    "extremaduran": "ext",
    "fang (equatorial guinea)": "fan",
    "fanti": "fat",
    "farefare": "gur",
    "fe'fe'": "fmp",
    "filipino": "fil",
    "filomena mata-coahuitlán totonac": "tlp",
    "finnish": "fi",
    "fipa": "fip",
    "french": "fr",
    "fulah": "ff",
    "galician": "gl",
    "gambian wolof": "wof",
    "ganda": "lg",
    "garhwali": "gbm",
    "gawar-bati": "gwt",
    "gawri": "gwc",
    "gbagyi": "gbr",
    "gbari": "gby",
    "geji": "gyz",
    "gen": "gej",
    "georgian": "ka",
    "german": "de",
    "geser-gorom": "ges",
    "gheg albanian": "aln",
    "ghomálá'": "bbj",
    "gidar": "gid",
    "glavda": "glw",
    "goan konkani": "gom",
    "goaria": "gig",
    "goemai": "ank",
    "gola": "gol",
    "greek": "el",
    "guarani": "gn",
    "guduf-gava": "gdf",
    "guerrero amuzgo": "amu",
    "gujarati": "gu",
    "gujari": "gju",
    "gulf arabic": "afb",
    "gurgula": "ggg",
    "gusii": "guz",
    "gusilay": "gsl",
    "gweno": "gwe",
    "güilá zapotec": "ztu",
    "hadothi": "hoj",
    "hahon": "hah",
    "haitian": "ht",
    "hakha chin": "cnh",
    "hakö": "hao",
    "halia": "hla",
    "hausa": "ha",
    "hawaiian": "haw",
    "hazaragi": "haz",
    "hebrew": "he",
    "hemba": "hem",
    "herero": "hz",
    "highland konjo": "kjk",
    "hijazi arabic": "acw",
    "hindi": "hi",
    "huarijio": "var",
    "huautla mazatec": "mau",
    "huaxcaleca nahuatl": "nhq",
    "huba": "hbb",
    "huitepec mixtec": "mxs",
    "hula": "hul",
    "hungarian": "hu",
    "hunjara-kaina ke": "hkk",
    "hwana": "hwo",
    "ibibio": "ibb",
    "icelandic": "is",
    "idakho-isukha-tiriki": "ida",
    "idoma": "idu",
    "igbo": "ig",
    "igo": "ahl",
    "ikposo": "kpo",
    "ikwere": "ikw",
    "imbabura highland quichua": "qvi",
    "indonesian": "id",
    "indus kohistani": "mvy",
    "interlingua (international auxiliary language association)": "ia",
    "inupiaq": "ik",
    "irish": "ga",
    "iron ossetic": "os",
    "isekiri": "its",
    "isoko": "iso",
    "italian": "it",
    "ito": "itw",
    "itzá": "itz",
    "ixtayutla mixtec": "vmj",
    "izon": "ijc",
    "jambi malay": "jax",
    "japanese": "ja",
    "jaqaru": "jqr",
    "jauja wanca quechua": "qxw",
    "jaunsari": "jns",
    "javanese": "jv",
    "jiba": "juo",
    "jju": "kaj",
    "judeo-moroccan arabic": "aju",
    "juxtlahuaca mixtec": "vmc",
    "kabardian": "kbd",
    "kabras": "lkb",
    "kabuverdianu": "kea",
    "kabyle": "kab",
    "kachi koli": "gjk",
    "kairak": "ckr",
    "kalabari": "ijn",
    "kalasha": "kls",
    "kalenjin": "kln",
    "kalkoti": "xka",
    "kamba": "kam",
    "kamo": "kcq",
    "kanauji": "bjj",
    "kanembu": "kbl",
    "kannada": "kn",
    "karekare": "kai",
    "kashmiri": "ks",
    "kathoriya tharu": "tkt",
    "kati": "bsh",
    "kazakh": "kk",
    "keiyo": "eyo",
    "khams tibetan": "khg",
    "khana": "ogo",
    "khetrani": "xhe",
    "khmer": "km",
    "khowar": "khw",
    "kinga": "zga",
    "kinnauri": "kfk",
    "kinyarwanda": "rw",
    "kirghiz": "ky",
    "kirya-konzəl": "fkk",
    "kochila tharu": "thq",
    "kohistani shina": "plk",
    "kohumono": "bcs",
    "kok borok": "trp",
    "kol (papua new guinea)": "kol",
    "kom (cameroon)": "bkm",
    "koma": "kmy",
    "konkani": "knn",
    "konzo": "koo",
    "korean": "ko",
    "korwa": "kfp",
    "kota (india)": "kfe",
    "koti": "eko",
    "kuanua": "ksd",
    "kuanyama": "kj",
    "kui (india)": "uki",
    "kulung (nigeria)": "bbu",
    "kuot": "kto",
    "kushi": "kuh",
    "kwambi": "kwm",
    "kwasio": "nmg",
    "lala-roba": "lla",
    "lamang": "hia",
    "lao": "lo",
    "larike-wakasihu": "alo",
    "lasi": "lss",
    "latgalian": "ltg",
    "latvian": "lv",
    "levantine arabic": "apc",
    "liana-seti": "ste",
    "liberia kpelle": "xpe",
    "liberian english": "lir",
    "libyan arabic": "ayl",
    "ligurian": "lij",
    "lijili": "mgi",
    "lingala": "ln",
    "lithuanian": "lt",
    "loarki": "lrk",
    "logooli": "rag",
    "logudorese sardinian": "src",
    "loja highland quichua": "qvj",
    "loloda": "loa",
    "longuda": "lnu",
    "loxicha zapotec": "ztp",
    "luba-lulua": "lua",
    "luo": "luo",
    "lushai": "lus",
    "luxembourgish": "lb",
    "maasina fulfulde": "ffm",
    "maba (chad)": "mde",
    "macedo-romanian": "rup",
    "macedonian": "mk",
    "mada (cameroon)": "mxu",
    "mafa": "maf",
    "maithili": "mai",
    "malay": "ms",
    "malayalam": "ml",
    "mali": "gcc",
    "malinaltepec me'phaa": "tcf",
    "maltese": "mt",
    "mandara": "tbf",
    "mandjak": "mfv",
    "manggarai": "mqy",
    "manipuri": "mni",
    "mansoanka": "msw",
    "manx": "gv",
    "maori": "mi",
    "marathi": "mr",
    "marghi central": "mrt",
    "marghi south": "mfm",
    "maria (india)": "mrr",
    "marwari (pakistan)": "mve",
    "masana": "mcn",
    "masikoro malagasy": "msh",
    "matsés": "mcf",
    "mazaltepec zapotec": "zpy",
    "mazatlán mazatec": "vmz",
    "mazatlán mixe": "mzl",
    "mbe": "mfo",
    "mbo (cameroon)": "mbo",
    "mbum": "mdd",
    "medumba": "byv",
    "mekeo": "mek",
    "meru": "mer",
    "mesopotamian arabic": "acm",
    "mewari": "mtr",
    "min nan chinese": "nan",
    "mingrelian": "xmf",
    "mitlatongo mixtec": "vmm",
    "miya": "mkf",
    "mokpwe": "bri",
    "moksha": "mdf",
    "mom jango": "ver",
    "mongolian": "mn",
    "moroccan arabic": "ary",
    "motu": "meu",
    "mpiemo": "mcx",
    "mpumpong": "mgg",
    "mundang": "mua",
    "mungaka": "mhk",
    "musey": "mse",
    "musgu": "mug",
    "musi": "mui",
    "naba": "mne",
    "najdi arabic": "ars",
    "nalik": "nal",
    "nawdm": "nmz",
    "ndonga": "ng",
    "neapolitan": "nap",
    "nepali": "npi",
    "ngamo": "nbh",
    "ngas": "anc",
    "ngiemboon": "nnh",
    "ngizim": "ngi",
    "ngomba": "jgo",
    "ngombale": "nla",
    "nigerian fulfulde": "fuv",
    "nigerian pidgin": "pcm",
    "nimadi": "noe",
    "nobiin": "fia",
    "north mesopotamian arabic": "ayp",
    "north moluccan malay": "max",
    "northern betsimisaraka malagasy": "bmm",
    "northern hindko": "hno",
    "northern kurdish": "kmr",
    "northern pame": "pmq",
    "northern pashto": "pbu",
    "northern uzbek": "uzn",
    "northwest gbaya": "gya",
    "norwegian": "no",
    "norwegian bokmål": "nb",
    "norwegian nynorsk": "nn",
    "notsi": "ncf",
    "nyankpa": "yes",
    "nyungwe": "nyu",
    "nzanyi": "nja",
    "nüpode huitoto": "hux",
    "occitan": "oc",
    "od": "odk",
    "odia": "ory",
    "odual": "odu",
    "omani arabic": "acx",
    "orizaba nahuatl": "nlv",
    "orma": "orc",
    "ormuri": "oru",
    "oromo": "om",
    "pahari-potwari": "phr",
    "paiwan": "pwn",
    "panjabi": "pa",
    "papuan malay": "pmy",
    "parkari koli": "kvx",
    "pedi": "nso",
    "pero": "pip",
    "persian": "fa",
    "petats": "pex",
    "phalura": "phl",
    "piemontese": "pms",
    "piya-kwonci": "piy",
    "plateau malagasy": "plt",
    "polish": "pl",
    "poqomam": "poc",
    "portuguese": "pt",
    "pulaar": "fuc",
    "pular": "fuf",
    "puno quechua": "qxp",
    "pushto": "ps",
    "pökoot": "pko",
    "qaqet": "byx",
    "quiotepec chinantec": "chq",
    "rana tharu": "thr",
    "rangi": "lag",
    "rapoisi": "kyx",
    "ratahan": "rth",
    "rayón zoque": "zor",
    "romanian": "ro",
    "romansh": "rm",
    "rombo": "rof",
    "rotokas": "roo",
    "rukai": "dru",
    "russian": "ru",
    "sacapulteco": "quv",
    "saidi arabic": "aec",
    "sakalava malagasy": "skg",
    "sakizaya": "szy",
    "saleman": "sau",
    "samba daka": "ccg",
    "samba leko": "ndi",
    "san felipe otlaltepec popoloca": "pow",
    "san francisco del mar huave": "hue",
    "san juan atzingo popoloca": "poe",
    "san martín itunyoso triqui": "trq",
    "san miguel el grande mixtec": "mig",
    "sansi": "ssi",
    "sanskrit": "sa",
    "santa ana de tusi pasco quechua": "qxt",
    "santa catarina albarradas zapotec": "ztn",
    "santali": "sat",
    "santiago del estero quichua": "qus",
    "saposa": "sps",
    "saraiki": "skr",
    "sardinian": "sc",
    "saya": "say",
    "sediq": "trv",
    "serbian": "sr",
    "seri": "sei",
    "shina": "scl",
    "shona": "sn",
    "siar-lak": "sjr",
    "sibe": "nco",
    "sicilian": "scn",
    "sihuas ancash quechua": "qws",
    "sikkimese": "sip",
    "sinaugoro": "snc",
    "sindhi": "sd",
    "sindhi bhil": "sbn",
    "sinhala": "si",
    "sinicahua mixtec": "xti",
    "sipacapense": "qum",
    "siwai": "siw",
    "slovak": "sk",
    "slovenian": "sl",
    "solos": "sol",
    "somali": "so",
    "soninke": "snk",
    "south giziga": "giz",
    "south ucayali ashéninka": "cpy",
    "southeastern nochixtlán mixtec": "mxy",
    "southern betsimisaraka malagasy": "bzc",
    "southern pashto": "pbt",
    "southern pastaza quechua": "qup",
    "soyaltepec mazatec": "vmp",
    "spanish": "es",
    "standard arabic": "arb",
    "standard moroccan tamazight": "zgh",
    "sudanese arabic": "apd",
    "sulka": "sua",
    "svan": "sva",
    "swahili": "sw",
    "swedish": "sv",
    "tae'": "rob",
    "tahaggart tamahaq": "thv",
    "taita": "dav",
    "tajik": "tg",
    "tamil": "ta",
    "tandroy-mahafaly malagasy": "tdx",
    "tangale": "tan",
    "tanosy malagasy": "txy",
    "tarok": "yer",
    "tatar": "tt",
    "tedaga": "tuq",
    "telugu": "te",
    "tem": "kdh",
    "teop": "tio",
    "tepeuxila cuicatec": "cux",
    "tepinapa chinantec": "cte",
    "tera": "ttr",
    "terei": "buo",
    "termanu": "twu",
    "tesaka malagasy": "tkg",
    "tetelcingo nahuatl": "nhg",
    "teutila cuicatec": "cut",
    "thai": "th",
    "tibetan": "bo",
    "tidaá mixtec": "mtx",
    "tidore": "tvo",
    "tigak": "tgc",
    "tigre": "tig",
    "tigrinya": "ti",
    "tilquiapan zapotec": "zts",
    "tinputz": "tpz",
    "tlacoapa me'phaa": "tpl",
    "tlacoatzintepec chinantec": "ctl",
    "tlingit": "tli",
    "toki pona": "tok",
    "tomoip": "tqp",
    "tondano": "tdn",
    "tonsea": "txs",
    "tooro": "ttj",
    "torau": "ttu",
    "torwali": "trw",
    "tsimihety malagasy": "xmw",
    "tsotso": "lto",
    "tswana": "tn",
    "tugen": "tuy",
    "tuki": "bag",
    "tula": "tul",
    "tulu": "tcy",
    "tunen": "tvu",
    "tungag": "lcm",
    "tunisian arabic": "aeb",
    "tupuri": "tui",
    "turkana": "tuv",
    "turkish": "tr",
    "turkmen": "tk",
    "tututepec mixtec": "mtu",
    "twi": "tw",
    "ubaghara": "byc",
    "uighur": "ug",
    "ukrainian": "uk",
    "umbundu": "umb",
    "upper sorbian": "hsb",
    "urdu": "ur",
    "ushojo": "ush",
    "uzbek": "uz",
    "vai": "vai",
    "vietnamese": "vi",
    "votic": "vot",
    "võro": "vro",
    "waci gbe": "wci",
    "wadiyara koli": "kxp",
    "waja": "wja",
    "wakhi": "wbl",
    "wanga": "lwg",
    "wapan": "juk",
    "warji": "wji",
    "welsh": "cy",
    "wemale": "weo",
    "western frisian": "fy",
    "western highland purepecha": "pua",
    "western juxtlahuaca mixtec": "jmx",
    "western maninkakan": "mlq",
    "western mari": "mrj",
    "western niger fulfulde": "fuh",
    "western panjabi": "pnb",
    "wolof": "wo",
    "wuzlam": "udl",
    "xanaguía zapotec": "ztg",
    "xhosa": "xh",
    "yace": "ekr",
    "yakut": "sah",
    "yalahatan": "jal",
    "yanahuanca pasco quechua": "qur",
    "yangben": "yav",
    "yaqui": "yaq",
    "yauyos quechua": "qux",
    "yekhee": "ets",
    "yiddish": "yi",
    "yidgha": "ydg",
    "yoruba": "yo",
    "yutanduchi mixtec": "mab",
    "zacatlán-ahuacatlán-tepetzintla nahuatl": "nhi",
    "zarma": "dje",
    "zaza": "zza",
    "zulu": "zu",
    "ömie": "aom"
}'''),
}

GUIDE_MARKDOWN = r'''
## OmniVoice: arbitrary reference voices, voice design, and every adapter control

This section describes the **pinned model and the duration-preserving Python adapter in this notebook**, not every option in other releases. There is **no finite speaker-ID catalog**: a clean recording of a single speaker provides a new reference voice. There is also a voice-design mode with the complete attribute vocabulary below. Similarity, pitch, and style adherence remain empirical; the model cannot guarantee an exact identity or a serious mood.

### Choose a voice

| Voice path | What you provide | What happens |
|---|---|---|
| Clone a recorded speaker | `ref_audio` and its exact `ref_text` | The codec turns the recording into a voice prompt. Use clean single-speaker speech; background music, overlapping voices, and an incorrect transcript can compromise pronunciation and similarity. |
| Reuse a clone | Existing `prompt_cache` `.pt` | Loads saved reference codec tokens, transcript, and RMS; original WAV and transcript arguments must be omitted. This avoids repeatedly preparing and encoding the reference. |
| Save a new clone | New `prompt_cache` path plus `ref_audio`/`ref_text` | The adapter prepares the reference during preflight; synthesis loads the model, encodes it, verifies the planned token count, and saves the cache. An estimate-only run does not encode/save a new prompt. |
| Design a voice | Comma-separated `instruct` attributes | Creates a voice matching supported attributes. Default: `male, middle-aged, low pitch, british accent`. Design has no fixed identity/preset ID. |
| Let the model choose | Explicit `instruct=""`, no reference | Resolves to upstream auto-voice mode. Omitting `instruct` or using `None` instead selects this adapter's male default. |

Upstream recommends **3–10 seconds** of reference audio; the shared notebook reference validator accepts **mono, finite, non-silent 1–8-second WAVs**. Choose **3–8 seconds** for both paths. The standalone adapter downmixes stereo and resamples to 24 kHz, then caps the prepared/cached reference token duration using `max_reference_seconds` (default 10). It rejects an oversized reference rather than truncating speech to fit. At least one 40 ms codec token is required. A same-language reference tends to give more standard pronunciation; a cross-language reference can transfer an accent. Clone mode is the upstream model's most stable mode; voice design was trained on English/Chinese and may be less stable in other languages. [Pinned cloning and language guidance](__SOURCE_BASE__/README.md)

To use a single reference for compatible models, set the notebook's global `reference_audio` and `reference_text`, with `speaker_mode="auto"`. In an OmniVoice profile, `reference` may be `"auto"`, `True`, or `False`; `True` requests a reference, `False` selects design unless a reference/cache is explicitly supplied or global `speaker_mode="reference"` forces cloning. A per-profile WAV uses `parameters={"ref_audio": "/kaggle/input/.../speaker.wav", "ref_text": "Exact transcript."}`. The automatic clone route removes default male design instructions. To deliberately combine a clone with matching attributes, use `clone_parameters={"instruct": "male, low pitch"}`. Conflicting attributes usually lose to the reference; matching dialect attributes can help. [Pinned combination tips](__SOURCE_BASE__/docs/tips.md)

### Complete voice-design attribute vocabulary

Choose **at most one value per category**. English values are case-insensitive. Chinese equivalents may be used; commas `,` or `，` are normalized. A dialect and an English accent cannot be combined. Unsupported emotion/style words such as `serious`, `angry`, `happy`, `sad`, `deep`, or `narrator` are rejected as instructions: use the actual pitch values or a reference recording with the desired delivery.

| Category | All accepted values, with Chinese equivalents where available |
|---|---|
| Gender | `male` / `男`; `female` / `女` |
| Age | `child` / `儿童`; `teenager` / `少年`; `young adult` / `青年`; `middle-aged` / `中年`; `elderly` / `老年` |
| Pitch | `very low pitch` / `极低音调`; `low pitch` / `低音调`; `moderate pitch` / `中音调`; `high pitch` / `高音调`; `very high pitch` / `极高音调` |
| Style | `whisper` / `耳语` |
| English accent | `american accent`, `british accent`, `australian accent`, `canadian accent`, `indian accent`, `chinese accent`, `korean accent`, `japanese accent`, `portuguese accent`, `russian accent` |
| Chinese dialect | `河南话`, `陕西话`, `四川话`, `贵州话`, `云南话`, `桂林话`, `济南话`, `石家庄话`, `甘肃话`, `宁夏话`, `青岛话`, `东北话` |

Accent controls apply to English speech; dialect controls apply to Chinese speech. Leaving a category out lets the model choose it. Some combinations may be ignored. [Pinned complete voice-design reference](__SOURCE_BASE__/docs/voice-design.md)

There are **no named emotion sliders and no per-word emphasis parameter** in this adapter. You can influence delivery with punctuation, a matching expressive reference, and these complete inline non-verbal tags:

`[laughter]`, `[sigh]`, `[confirmation-en]`, `[question-en]`, `[question-ah]`, `[question-oh]`, `[question-ei]`, `[question-yi]`, `[surprise-ah]`, `[surprise-oh]`, `[surprise-wa]`, `[surprise-yo]`, `[dissatisfaction-hnn]`.

English pronunciation may be overridden with bracketed uppercase CMU phonemes, e.g. `[B EY1 S]`; Chinese pronunciations can use pinyin tone numbers. These are pronunciation/non-verbal controls, not general emotion labels or SSML. The chunker preserves complete bracket groups. [Pinned inline-control examples](__SOURCE_BASE__/README.md)

### Generation and planning controls

Keys use underscores in a profile `parameters` dictionary; the standalone CLI uses hyphens. “Default” below means **standalone script default**. The enabled notebook profile changes `num_step` to **64**, `max_chunk_seconds` to **12.0**, and `dtype` to **float16**; export is **48,000 Hz** via the global configuration. Unspecified values retain script defaults.

| Key | Default; accepted values | Exactly what it changes |
|---|---|---|
| `language` | `"en"`; one supported ID/name, or `"none"`/`None` | Language conditioning. Full names are case-insensitive; use the lower-case IDs in the full catalog below. `none` omits language conditioning. Unknown non-null values are rejected by the adapter. It does not translate text. |
| `instruct` | Male design above; supported attributes or `""` | Voice-design conditioning. Empty string requests auto voice. With a clone, matching instructions may reinforce the reference; the notebook's clone route removes design defaults unless explicitly provided in `clone_parameters`. |
| `ref_audio` | `None`; readable audio path | Recorded speaker prompt. Requires `ref_text`. File loading/downmixing/resampling/preprocessing occurs before planning; first use is not an instant text-only preview. |
| `ref_text` | `None`; exact nonempty transcript | The words spoken in the reference, not the text to synthesize. Required with new audio, forbidden without audio. The adapter does not load automatic reference ASR. A cache already contains this transcript. |
| `prompt_cache` | `None`; existing/new `.pt` path | Existing path loads a clone and forbids supplying new audio simultaneously. Missing path requires new audio/transcript and is written after reference encoding for synthesis. Cached shape must be 8 codebooks by positive token count. |
| `preprocess_prompt` | `True`; boolean | Removes long reference silences (upstream 200 ms interior/200 ms trailing/100 ms leading handling) and adds terminal punctuation if missing. Changing it changes reference token count and therefore rule-based duration allocation. Existing cache is already prepared and is unaffected. Does not remove generated silence. |
| `normalize_text` | `False`; boolean | Expands numbers/symbols to spoken forms before both planning and synthesis, while preserving inline tags/phonemes/pinyin. English/Chinese require optional OmniVoice `[tn]` dependencies; this notebook does not install that extra by default. Other languages use a best-effort integer conversion when `num2words` supports them. Inspect the logged normalized text; no universal normalization is promised. |
| `speed` | `1.0`; finite `>0` | Divides rule-estimated token allocation: above 1 shortens planned speech, below 1 lengthens it. This is token allocation, not playback-speed resampling. Ignored when `duration` is set. Extreme values can cause rushed/missing speech or surplus silence. |
| `duration` | `None`; finite seconds `>0` | Overrides speed and allocates `max(1, floor(duration*25))` speech tokens across chunks: **40 ms resolution**, before explicitly added inter-chunk pauses. The final file may therefore differ from the literal requested float; the reported sample-count preview is the exact planned export. Too few tokens for the required chunks are rejected. |
| `max_chunk_seconds` | `8.0`; finite `>=0.04` | Maximum planned speech-token duration per manual chunk, rounded down to whole tokens. Smaller values lower context/VRAM costs but produce more boundaries; larger values provide longer context at higher memory cost. Splits prefer sentence/clause boundaries; short terminal chunks are rebalanced when feasible. Changing it can change total allocation through per-chunk rounding and the short-text rule. |
| `max_reference_seconds` | `10.0`; finite `>0` | Rejects prepared/cached prompts whose token duration exceeds the cap. Does not shorten the WAV, set output duration, or guarantee memory usage. Raising it admits longer references and can raise VRAM/inference cost. |
| `num_step` | `32`; integer `>=1` | Number of neural iterative unmasking passes per chunk; 64 in the notebook quality profile. More passes cost more generation time and may improve quality; they do not change frozen token lengths or guarantee monotonic improvement. |
| `guidance_scale` | `2.0`; finite `>=0` | Conditioning extrapolation uses `conditional_logp + scale*(conditional_logp-unconditional_logp)` before normalization. Zero uses the conditional prediction alone; larger values strengthen the difference. Token length stays fixed. Upstream still builds conditional/unconditional inputs, so zero is not a guaranteed half-memory mode. |
| `t_shift` | `0.1`; finite `>0` | Warps a linear time grid by `a*t/(1+(a-1)*t)`. This changes how many masked positions are committed at each iteration. `1.0` is linear; below 1 produces smaller early increments and larger late increments in this pinned implementation. It does not change target duration. |
| `layer_penalty_factor` | `5.0`; finite `>=0` | Subtracts `codebook_index*factor` from selection scores. Larger values favor filling earlier codec codebooks first. Zero removes that ordering preference. Duration remains fixed. |
| `position_temperature` | `5.0`; finite `>=0` | Controls Gumbel randomness in deciding which masked positions to commit. Zero chooses positions greedily; larger values add more randomness. Different seeds can vary waveform content despite identical length. |
| `class_temperature` | `0.0`; finite `>=0` | Zero chooses the most likely token value. Positive values sample using Gumbel noise after a fixed top-10%-of-vocabulary filter. Controls token diversity, separately from which positions get filled; length remains fixed. |
| `denoise` | `True`; boolean | Adds a model conditioning token when reference tokens are present, requesting cleaner speech. It is not a waveform denoising filter. It has no such token effect for a reference-free first chunk; later design/auto chunks use the first generated chunk as a prompt. |
| `fade_ms` | `10.0`; finite `[0,20]` | Applies length-preserving amplitude fades at each manual chunk edge. Zero disables fades. Helps boundary clicks; long fades can attenuate first/last phonemes. No samples are removed or crossfaded away. |
| `peak_limit` | `0.98`; finite `(0,1]` | After export resampling, attenuates the entire WAV only if its absolute peak exceeds this ceiling. Logs gain/original peak. Prevents overdrive; does not restore distorted source speech, compress dynamics, or change length. |
| `sample_rate` | `None` = native **24,000 Hz**; integer `[8000,192000]` | Rational resampling for the exported WAV; 48,000 in the notebook. Codec bandwidth remains native. The planner includes the exact rounded output sample count. This is unrelated to generation temperature. |
| `pause_ms` | `0.0`; finite `>=0` | Adds this rounded number of milliseconds of zero samples **between manual chunks only**. Included in preview. It does not control pauses inside a chunk or strip model-produced gaps. Zero avoids deliberately adding boundary gaps. |
| `dtype` | `"auto"`; `auto`, `float32`, `float16`, `bfloat16` | Auto selects float32 on CPU and float16 on CUDA. Float16 CPU is rejected. Float16 is the tested/configured T4 path; other dtypes require compatible hardware/runtime. Dtype affects compute/memory, not planned sample length. |

Decoder and scheduling behavior above was checked against the [pinned model implementation](__SOURCE_BASE__/omnivoice/models/omnivoice.py), not inferred from the parameter names alone. [Upstream parameter reference](__SOURCE_BASE__/docs/generation-parameters.md)

**Why the duration preview can be exact:** without explicit duration, the adapter applies the pinned Unicode-weight/reference-rate rule, freezes per-chunk target tokens, then generates exactly those tokens. With explicit duration it freezes an allocation from your requested seconds. Native output is 960 samples per 25 Hz token at 24 kHz. Planned pauses and rational export resampling are included. Changing seed, steps, guidance, or temperatures changes content while keeping this allocation fixed. A changed reference, preprocessing, normalization, text, speed, chunk bound, or duration requires a new plan. Short-text allocation includes the upstream nonlinear boost below 50 tokens. A cached prompt avoids re-encoding; imports/reference work still make cold preflight slower than warm arithmetic. **Exact length does not certify complete words, natural pacing, or an independently accurate prediction of unconstrained speech.** [Pinned rule allocator](__SOURCE_BASE__/omnivoice/utils/duration.py)

The adapter deliberately disables upstream `postprocess_output` (silence removal), `pad_duration` (extra edge silence), and automatic `audio_chunk_duration`/`audio_chunk_threshold` chunking. It fixes them to `False`, `0.0`, `0.0`, and infinity, respectively, so output remains sample-exact. They are **not configurable adapter keys**; passing them raises an unknown-key error. `fade_duration` is exposed as `fade_ms`; `preprocess_prompt` is applied while preparing the reference, then disabled at generation to avoid applying it twice. Other upstream-only choices—automatic reference ASR, FlashInfer/CUDA graphs, user batch size, training/fine-tuning, and multi-speaker dialogue—are not exposed by this benchmark adapter.

### Common execution controls present in the OmniVoice script

The notebook supervisor supplies text, take count, seeds, output directories, local assets, and the visible GPU device. Override generation controls in each profile rather than overriding supervisor bookkeeping.

| Key | Script default / bounds | Purpose |
|---|---|---|
| `text`, `text_file` | Exactly one required; nonempty, at most 500 whitespace-delimited words | Direct input string or UTF-8 text-file path. The notebook tests complete 10/100/500-word passages. |
| `config` | None; JSON object path | Loads underscore/hyphen CLI destination keys; explicit CLI values override JSON. Unknown keys and wrong types fail. `help`, `config`, and `self_test` cannot be supplied inside this JSON. |
| `n` | `1`; integer `>=1` | Number of output takes, each reusing the same plan. |
| `seed` | `1234`; integers with `0 <= seed` and `seed+n-1 < 2**32` | Successive take seeds are `seed`, `seed+1`, etc.; seeds are set for Torch/NumPy/CUDA. Greedy settings can reduce variation. Reproducibility across hardware is not guaranteed. |
| `device` | `"cpu"`; `cpu`, `cuda`, `cuda:N` | Execution target. The notebook worker hides the other GPU, so `cuda:0` refers to its assigned physical T4. |
| `max_vram_gb` | `5.0`; finite `(0,5]`, decimal GB | Caps PyTorch's allocator with a context reserve; the notebook additionally samples whole-device NVML usage and kills over-budget jobs. Neither mechanism certifies an unobserved instantaneous driver/library peak. |
| `output_dir` | `outputs/omnivoice`; path | Writes estimate/manifest and numbered seed-labelled float WAVs. Existing intended sample paths are rejected to prevent silent overwrite. |
| `estimate_only` | `False`; boolean | Writes the plan without loading weights or generating speech. New-reference audio work and dependencies can still be needed; an existing prompt cache requires the pinned package but not reference re-encoding. |
| `local_model` | `None`; directory | Uses a local pinned-model snapshot including the official `audio_tokenizer/config.json`. Otherwise downloads the pinned Hugging Face revision. A different checkpoint is not an audited guarantee. |
| `local_files_only` | `False`; boolean | Restricts Hugging Face snapshot retrieval to cache; notebook predownloads assets and sets this true. |
| `self_test` | `False`; CLI flag only | Runs dependency-free arithmetic and chunking sanity checks, not model-quality or GPU validation. |
| `help` | CLI `--help` | Prints standalone CLI usage and exits; not a JSON/profile generation setting. |

### All supported OmniVoice language IDs and names

The pinned mapping contains **646 IDs and 646 names**. Examples relevant to this setup: `en` (English), `fa` (Persian), `zh` (Chinese), `ja` (Japanese), `de` (German), `fr` (French), `es` (Spanish), `hi` (Hindi), `ru` (Russian). Language coverage does not imply uniform accent or quality. Min Nan Chinese (`nan`) requires Tai-lo romanized input in this release. The complete frozen mapping is shown below and is also present in the notebook's machine-readable voice catalog. [Pinned language mapping](__SOURCE_BASE__/omnivoice/utils/lang_map.py)

<details>
<summary>Expand all 646 accepted language IDs and names</summary>

__LANGUAGE_TABLE__

</details>
'''.replace("__SOURCE_BASE__", SOURCE_BASE).strip()

_language_rows = "\n".join(
    f"| `{code}` | {name.title()} |"
    for name, code in sorted(VOICE_CATALOG["language_name_to_id"].items(), key=lambda item: (item[1], item[0]))
)
GUIDE_MARKDOWN = GUIDE_MARKDOWN.replace(
    "__LANGUAGE_TABLE__", "| ID | Accepted full name |\n|---|---|\n" + _language_rows
)
